"use client";

import { useState } from "react";
import Link from "next/link";
import { JsonLd } from "@/components/json-ld";
import { ToolCTA } from "@/components/tool-cta";

interface Goal {
  id: number;
  category: string;
  metric: string;
  current: string;
  target: string;
  deadline: string;
  strategy: string;
  owner: string;
  milestones: string;
}

const goalCategories = [
  {
    name: "Traffic",
    metrics: ["Monthly website visitors", "Organic search traffic", "Referral traffic", "Social media traffic", "Paid traffic"],
  },
  {
    name: "Leads",
    metrics: ["Monthly leads generated", "Marketing qualified leads (MQLs)", "Sales qualified leads (SQLs)", "Email subscribers", "Demo requests"],
  },
  {
    name: "Revenue",
    metrics: ["Monthly revenue", "Customer acquisition cost (CAC)", "Customer lifetime value (LTV)", "Return on ad spend (ROAS)", "Average order value"],
  },
  {
    name: "Brand",
    metrics: ["Brand search volume", "Social media followers", "Share of voice", "Net promoter score (NPS)", "Media mentions"],
  },
  {
    name: "Engagement",
    metrics: ["Email open rate", "Email click rate", "Social engagement rate", "Website conversion rate", "Time on site"],
  },
];

const timeframes = ["30 days", "60 days", "90 days", "6 months", "12 months"];

let nextGoalId = 1;

function emptyGoal(): Goal {
  return {
    id: nextGoalId++,
    category: "",
    metric: "",
    current: "",
    target: "",
    deadline: "",
    strategy: "",
    owner: "",
    milestones: "",
  };
}

function isSmartComplete(g: Goal): { specific: boolean; measurable: boolean; achievable: boolean; relevant: boolean; timeBound: boolean } {
  return {
    specific: !!(g.category && g.metric),
    measurable: !!(g.current && g.target),
    achievable: !!g.strategy,
    relevant: !!g.category,
    timeBound: !!g.deadline,
  };
}

export default function MarketingGoalSetterPage() {
  const [goals, setGoals] = useState<Goal[]>([emptyGoal()]);
  const [activeGoal, setActiveGoal] = useState(0);
  const [showSummary, setShowSummary] = useState(false);

  const updateGoal = (field: keyof Goal, value: string) => {
    setGoals((prev) =>
      prev.map((g, i) => (i === activeGoal ? { ...g, [field]: value } : g))
    );
  };

  const addGoal = () => {
    setGoals((prev) => [...prev, emptyGoal()]);
    setActiveGoal(goals.length);
  };

  const removeGoal = (index: number) => {
    if (goals.length <= 1) return;
    setGoals((prev) => prev.filter((_, i) => i !== index));
    setActiveGoal(Math.min(activeGoal, goals.length - 2));
  };

  const goal = goals[activeGoal];
  const selectedCategory = goalCategories.find((c) => c.name === goal?.category);
  const smart = goal ? isSmartComplete(goal) : { specific: false, measurable: false, achievable: false, relevant: false, timeBound: false };
  const smartCount = Object.values(smart).filter(Boolean).length;

  const downloadPlan = () => {
    const lines = [
      "MARKETING GOAL PLAN",
      "====================",
      "",
    ];
    goals.forEach((g, i) => {
      const s = isSmartComplete(g);
      const sc = Object.values(s).filter(Boolean).length;
      lines.push(`--- Goal ${i + 1} ---`);
      lines.push(`Category: ${g.category || "N/A"}`);
      lines.push(`Metric: ${g.metric || "N/A"}`);
      lines.push(`Current: ${g.current || "N/A"}`);
      lines.push(`Target: ${g.target || "N/A"}`);
      lines.push(`Deadline: ${g.deadline || "N/A"}`);
      lines.push(`Strategy: ${g.strategy || "N/A"}`);
      lines.push(`Owner: ${g.owner || "N/A"}`);
      lines.push(`Milestones: ${g.milestones || "N/A"}`);
      lines.push(`SMART Score: ${sc}/5`);
      lines.push("");
    });
    lines.push("--- Generated by Markit Media (themarkitmedia.com) ---");
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "marketing-goal-plan.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <article className="px-6 lg:px-12 py-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "Marketing Goal Setter",
          description: "Set SMART marketing goals with structured templates for traffic, leads, revenue, brand awareness, and engagement. Track progress and export your goal plan.",
          url: "https://themarkitmedia.com/en/resources/marketing-goal-setter",
          applicationCategory: "Marketing Tool",
          operatingSystem: "Web",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          provider: { "@type": "Organization", name: "Markit Media", url: "https://themarkitmedia.com" },
        }) }}
      />
      <div className="max-w-4xl mx-auto">
        <nav aria-label="Breadcrumb" className="text-base text-gray-400 mb-8">
          <Link href="/resources" className="hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Resources</Link>
          <span className="mx-2">/</span>
          <span className="text-black">Marketing Goal Setter</span>
        </nav>

        <header className="mb-12">
          <p className="text-base font-semibold tracking-widest uppercase text-gray-400 mb-3">Free Planning Tool</p>
          <h1 className="font-[family-name:var(--font-display)] text-[clamp(2rem,5vw,3.5rem)] font-extrabold text-black tracking-tight leading-[1.1]">
            Marketing Goal Setter
          </h1>
          <p className="text-lg text-gray-500 mt-4 max-w-2xl">
            Set SMART marketing goals with measurable targets, deadlines, and strategies. Track multiple goals and export your plan.
          </p>
        </header>

        {!showSummary ? (
          <div className="space-y-6">
            <div className="flex flex-wrap items-center gap-2 border-b border-gray-200 pb-3">
              {goals.map((g, i) => (
                <button key={g.id} onClick={() => setActiveGoal(i)} className={`px-4 py-2 text-base font-medium border transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2 ${activeGoal === i ? "bg-black text-white border-black" : "border-gray-300 text-gray-700 hover:border-black"}`}>
                  Goal {i + 1}{g.metric ? `: ${g.metric.slice(0, 20)}` : ""}
                </button>
              ))}
              <button onClick={addGoal} className="px-4 py-2 text-base font-medium border border-dashed border-gray-300 text-gray-500 hover:border-black hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">+ Add Goal</button>
            </div>

            {goal && (
              <section aria-label="Content section" className="border border-gray-200 p-6 lg:p-8 space-y-5">
                <div className="flex items-center gap-2 mb-2">
                  {["S", "M", "A", "R", "T"].map((letter, i) => {
                    const keys: (keyof typeof smart)[] = ["specific", "measurable", "achievable", "relevant", "timeBound"];
                    const filled = smart[keys[i]];
                    return (
                      <div key={letter} className={`w-8 h-8 flex items-center justify-center text-base font-bold ${filled ? "bg-black text-white" : "bg-gray-100 text-gray-400"}`}>
                        {letter}
                      </div>
                    );
                  })}
                  <span className="text-base text-gray-400 ml-2">{smartCount}/5 SMART criteria met</span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Goal Category</label>
                    <select value={goal.category} onChange={(e) => { updateGoal("category", e.target.value); updateGoal("metric", ""); }} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black bg-white">
                      <option value="">Select category</option>
                      {goalCategories.map((c) => <option key={c.name} value={c.name}>{c.name}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Specific Metric</label>
                    <select value={goal.metric} onChange={(e) => updateGoal("metric", e.target.value)} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black bg-white" disabled={!selectedCategory}>
                      <option value="">Select metric</option>
                      {selectedCategory?.metrics.map((m) => <option key={m} value={m}>{m}</option>)}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Current Value</label>
                    <input type="text" value={goal.current} onChange={(e) => updateGoal("current", e.target.value)} placeholder="e.g. 5,000 visitors/month" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                  </div>
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Target Value</label>
                    <input type="text" value={goal.target} onChange={(e) => updateGoal("target", e.target.value)} placeholder="e.g. 10,000 visitors/month" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Timeframe</label>
                    <select value={goal.deadline} onChange={(e) => updateGoal("deadline", e.target.value)} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black bg-white">
                      <option value="">Select timeframe</option>
                      {timeframes.map((t) => <option key={t} value={t}>{t}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Owner / Responsible</label>
                    <input type="text" value={goal.owner} onChange={(e) => updateGoal("owner", e.target.value)} placeholder="e.g. Marketing Manager" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                  </div>
                </div>

                <div>
                  <label className="block text-base font-bold text-black mb-2">Strategy / How to Achieve</label>
                  <textarea value={goal.strategy} onChange={(e) => updateGoal("strategy", e.target.value)} placeholder="What specific actions will you take to reach this goal?" rows={3} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black resize-y" />
                </div>

                <div>
                  <label className="block text-base font-bold text-black mb-2">Key Milestones</label>
                  <textarea value={goal.milestones} onChange={(e) => updateGoal("milestones", e.target.value)} placeholder="e.g. Month 1: 6,000 visitors, Month 2: 8,000 visitors, Month 3: 10,000 visitors" rows={2} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black resize-y" />
                </div>

                {goals.length > 1 && (
                  <button onClick={() => removeGoal(activeGoal)} className="text-base text-gray-400 hover:text-red-600 transition-colors">Remove this goal</button>
                )}
              </section>
            )}

            <button onClick={() => setShowSummary(true)} disabled={!goals.some((g) => g.metric && g.target)} className="bg-black text-white px-8 py-4 text-base font-bold hover:bg-gray-800 transition-colors disabled:opacity-40 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">
              View Goal Summary &rarr;
            </button>
          </div>
        ) : (
          <div className="space-y-8">
            <section aria-label="Your Marketing Goals" className="border border-gray-200 p-6 lg:p-8">
              <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-black mb-6">Your Marketing Goals</h2>
              <div className="space-y-6">
                {goals.map((g, i) => {
                  const s = isSmartComplete(g);
                  const sc = Object.values(s).filter(Boolean).length;
                  return (
                    <div key={g.id} className="border border-gray-100 p-5">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-base font-bold text-black">Goal {i + 1}: {g.metric || "Unnamed"}</h3>
                        <div className="flex items-center gap-2">
                          {["S", "M", "A", "R", "T"].map((letter, li) => {
                            const keys: (keyof typeof s)[] = ["specific", "measurable", "achievable", "relevant", "timeBound"];
                            return (
                              <div key={letter} className={`w-6 h-6 flex items-center justify-center text-base font-bold ${s[keys[li]] ? "bg-black text-white" : "bg-gray-100 text-gray-300"}`}>
                                {letter}
                              </div>
                            );
                          })}
                          <span className="text-base text-gray-400 ml-1">{sc}/5</span>
                        </div>
                      </div>
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-base">
                        {g.category && <div><span className="text-gray-500">Category:</span> {g.category}</div>}
                        {g.current && <div><span className="text-gray-500">Current:</span> {g.current}</div>}
                        {g.target && <div><span className="text-gray-500">Target:</span> {g.target}</div>}
                        {g.deadline && <div><span className="text-gray-500">Deadline:</span> {g.deadline}</div>}
                      </div>
                      {g.strategy && <p className="text-base text-gray-600 mt-2"><span className="text-gray-500">Strategy:</span> {g.strategy}</p>}
                      {g.milestones && <p className="text-base text-gray-600 mt-1"><span className="text-gray-500">Milestones:</span> {g.milestones}</p>}
                    </div>
                  );
                })}
              </div>
            </section>

            <div className="flex flex-wrap gap-4">
              <button onClick={downloadPlan} className="bg-black text-white px-8 py-3 text-base font-bold hover:bg-gray-800 transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Download Plan (.txt)</button>
              <button onClick={() => setShowSummary(false)} className="border border-gray-300 text-gray-700 px-6 py-3 text-base font-medium hover:border-black hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Edit Goals</button>
            </div>

            <section aria-label="Need Help Hitting Your Goals?" className="bg-black text-white p-8 lg:p-12 text-center">
              <h2 className="font-[family-name:var(--font-display)] text-2xl font-extrabold mb-4">Need Help Hitting Your Goals?</h2>
              <p className="text-lg text-gray-300 mb-8 max-w-xl mx-auto">Our team builds data-driven strategies to help you reach your marketing targets on time and on budget.</p>
              <Link href="/contact" className="inline-block bg-white text-black px-10 py-5 text-base font-bold hover:bg-gray-100 transition-colors focus-visible:outline-2 focus-visible:outline-white focus-visible:outline-offset-2">Plan Your Strategy &rarr;</Link>
            </section>
          </div>
        )}
      </div>
          <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "Marketing Goal Setter",
          description: "Set SMART marketing goals with structured templates for traffic, leads, revenue, brand awareness, and engagement. Track progress and export your goal plan.",
          applicationCategory: "MarketingApplication",
          operatingSystem: "Any",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        }}
      />
    
      <ToolCTA
        toolName="Marketing Goal Setter"
        services={[
          { title: "Digital Marketing", desc: "Data-driven strategy with transparent reporting and insights.", href: "/services/digital-marketing" },
          { title: "Performance Marketing", desc: "Campaign optimization based on real performance data.", href: "/services/performance-marketing" },
          { title: "SEO", desc: "SEO analytics that show exactly what drives organic growth.", href: "/services/seo" },
        ]}
        relatedTools={[
          { title: "Marketing Budget Planner", href: "/resources/marketing-budget-planner" },
          { title: "Marketing Kpi Tracker", href: "/resources/marketing-kpi-tracker" },
          { title: "Marketing Metrics Benchmark", href: "/resources/marketing-metrics-benchmark" },
        ]}
        relatedBlog={[
          { title: "Digital Marketing Strategy Guide", href: "/blog" },
          { title: "How to Measure Marketing ROI", href: "/blog" },
        ]}
      />
    </article>
  );
}
