import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256],
    minimumCacheTTL: 31536000,
  },
  poweredByHeader: false,
  serverExternalPackages: ["better-sqlite3"],
  outputFileTracingIncludes: {
    "/api/**": ["./data/**"],
    "/feed.xml": ["./data/**"],
  },
  experimental: {
    optimizePackageImports: ["lucide-react"],
  },
  async headers() {
    const csp = [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: https://www.googletagmanager.com https://i.ytimg.com https://img.youtube.com",
      "font-src 'self'",
      "connect-src 'self' https://www.googletagmanager.com https://www.google-analytics.com https://analytics.google.com",
      "frame-src https://www.googletagmanager.com https://www.youtube.com",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
    ].join("; ");

    const securityHeaders = [
      { key: "X-Content-Type-Options", value: "nosniff" },
      { key: "X-Frame-Options", value: "DENY" },
      { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
      { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
      { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
      { key: "X-DNS-Prefetch-Control", value: "on" },
      { key: "Content-Security-Policy", value: csp },
    ];
    return [
      { source: "/(.*)", headers: securityHeaders },
      { source: "/images/:path*", headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }] },
      { source: "/fonts/:path*", headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }] },
      { source: "/admin/:path*", headers: [{ key: "X-Robots-Tag", value: "noindex, nofollow" }] },
      { source: "/ar/:path*", headers: [{ key: "X-Robots-Tag", value: "noindex, nofollow" }] },
      { source: "/ur/:path*", headers: [{ key: "X-Robots-Tag", value: "noindex, nofollow" }] },
    ];
  },
  async redirects() {
    return [
      // === Old page slugs (from Wayback Machine + Google index) ===
      { source: "/about-us", destination: "/en/about", permanent: true },
      { source: "/about-markit-media", destination: "/en/about", permanent: true },
      { source: "/contact-us", destination: "/en/contact", permanent: true },
      { source: "/contact-2", destination: "/en/contact", permanent: true },
      { source: "/our-services", destination: "/en/services", permanent: true },
      { source: "/services", destination: "/en/services", permanent: true },
      { source: "/our-work", destination: "/en/work", permanent: true },
      { source: "/our-team", destination: "/en/about", permanent: true },
      { source: "/get-quote", destination: "/en/get-a-quote", permanent: true },
      { source: "/request-quote", destination: "/en/get-a-quote", permanent: true },
      { source: "/free-consultation", destination: "/en/get-a-quote", permanent: true },
      { source: "/marketing-consultation", destination: "/en/get-a-quote", permanent: true },
      { source: "/home", destination: "/en", permanent: true },
      { source: "/team", destination: "/en/about", permanent: true },
      { source: "/our-clients", destination: "/en/work", permanent: true },
      { source: "/cases", destination: "/en/work", permanent: true },
      { source: "/career", destination: "/en/careers", permanent: true },
      { source: "/jobs", destination: "/en/careers", permanent: true },
      { source: "/internship", destination: "/en/careers", permanent: true },
      { source: "/faq", destination: "/en/faq", permanent: true },
      { source: "/why-choose-us", destination: "/en/why-markit-media", permanent: true },
      { source: "/how-it-works", destination: "/en/process", permanent: true },
      { source: "/our-process", destination: "/en/process", permanent: true },
      { source: "/industries", destination: "/en/industries", permanent: true },
      { source: "/industries-we-serve", destination: "/en/industries", permanent: true },
      { source: "/markit-media", destination: "/en/about", permanent: true },
      { source: "/terms-and-conditions", destination: "/en/terms", permanent: true },
      { source: "/terms-and-condition", destination: "/en/terms", permanent: true },
      { source: "/terms-of-service", destination: "/en/terms", permanent: true },
      { source: "/cookie-policy", destination: "/en/privacy-policy", permanent: true },
      { source: "/disclaimer", destination: "/en/terms", permanent: true },
      { source: "/sitemap", destination: "/sitemap.xml", permanent: true },
      { source: "/sample-page", destination: "/en", permanent: true },
      { source: "/hello-world", destination: "/en/blog", permanent: true },
      { source: "/blog-2", destination: "/en/blog", permanent: true },
      { source: "/blogs", destination: "/en/blog", permanent: true },
      { source: "/news", destination: "/en/blog", permanent: true },
      { source: "/media", destination: "/en/about", permanent: true },
      { source: "/press", destination: "/en/about", permanent: true },
      { source: "/newsletter", destination: "/en/blog", permanent: true },
      { source: "/subscribe", destination: "/en/contact", permanent: true },
      { source: "/testimonials", destination: "/en/work", permanent: true },
      { source: "/reviews", destination: "/en/work", permanent: true },
      { source: "/pricing", destination: "/en/pricing", permanent: true },
      { source: "/packages", destination: "/en/get-a-quote", permanent: true },
      { source: "/service-areas", destination: "/en/locations", permanent: true },
      { source: "/usa", destination: "/en/locations/united-states", permanent: true },
      { source: "/login", destination: "/en", permanent: false },
      { source: "/register", destination: "/en", permanent: false },

      // === Old service pages (service-* pattern from WordPress) ===
      { source: "/service-seo", destination: "/en/services/seo", permanent: true },
      { source: "/service-seo-audit", destination: "/en/services/seo/seo-audits", permanent: true },
      { source: "/service-on-page-seo", destination: "/en/services/seo/content-seo", permanent: true },
      { source: "/service-off-page-seo", destination: "/en/services/seo/link-building", permanent: true },
      { source: "/service-local-seo", destination: "/en/services/seo/local-seo", permanent: true },
      { source: "/service-keywords-research", destination: "/en/services/seo/keyword-research", permanent: true },
      { source: "/service-digital-marketing", destination: "/en/services/digital-marketing", permanent: true },
      { source: "/service-lead-generation", destination: "/en/services/digital-marketing", permanent: true },
      { source: "/service-google-ppc", destination: "/en/services/performance-marketing/google-ads", permanent: true },
      { source: "/service-meta-ads-facebook-ads", destination: "/en/services/performance-marketing/meta-ads", permanent: true },
      { source: "/service-meta-ads-facebook-ads-instagram-ads", destination: "/en/services/performance-marketing/meta-ads", permanent: true },
      { source: "/service-instagram-ads", destination: "/en/services/performance-marketing/meta-ads", permanent: true },
      { source: "/service-linkedin-ads", destination: "/en/services/performance-marketing/linkedin-ads", permanent: true },
      { source: "/service-tiktok-ads", destination: "/en/services/performance-marketing/tiktok-ads", permanent: true },
      { source: "/service-social-media", destination: "/en/services/social-media", permanent: true },
      { source: "/service-social-media-marketin", destination: "/en/services/social-media", permanent: true },
      { source: "/service-social-media-design", destination: "/en/services/social-media/content-creation", permanent: true },
      { source: "/service-social-media/:path*", destination: "/en/services/social-media", permanent: true },
      { source: "/service-website-development", destination: "/en/services/website-development", permanent: true },
      { source: "/service-website-development/:path*", destination: "/en/services/website-development", permanent: true },
      { source: "/service-custom-website-design", destination: "/en/services/website-development", permanent: true },
      { source: "/service-custom-website-development", destination: "/en/services/website-development", permanent: true },
      { source: "/service-custom-websites", destination: "/en/services/website-development", permanent: true },
      { source: "/service-custom-ecommerce-website", destination: "/en/services/website-development/ecommerce", permanent: true },
      { source: "/service-ecommerce-web-designs", destination: "/en/services/website-development/ecommerce", permanent: true },
      { source: "/service-ecommerce-web-development", destination: "/en/services/website-development/ecommerce", permanent: true },
      { source: "/service-shopify", destination: "/en/services/website-development/shopify", permanent: true },
      { source: "/service-shopify-design", destination: "/en/services/website-development/shopify", permanent: true },
      { source: "/service-shopify-development", destination: "/en/services/website-development/shopify", permanent: true },
      { source: "/service-shopify-marketing", destination: "/en/services/ecommerce-marketing/shopify-marketing", permanent: true },
      { source: "/service-wordpress", destination: "/en/services/website-development/wordpress", permanent: true },
      { source: "/service-wordpress-development", destination: "/en/services/website-development/wordpress", permanent: true },
      { source: "/service-wordpress-web-designs", destination: "/en/services/website-development/wordpress", permanent: true },
      { source: "/service-next-js", destination: "/en/services/website-development/nextjs", permanent: true },
      { source: "/service-magento", destination: "/en/services/website-development", permanent: true },
      { source: "/service-squarespace", destination: "/en/services/website-development", permanent: true },
      { source: "/service-wix", destination: "/en/services/website-development", permanent: true },
      { source: "/service-php-custom", destination: "/en/services/website-development/custom-web-apps", permanent: true },
      { source: "/service-website-migration", destination: "/en/services/website-development", permanent: true },
      { source: "/service-website-redirects", destination: "/en/services/website-development", permanent: true },
      { source: "/service-custom-shirt-website-services", destination: "/en/services/website-development/ecommerce", permanent: true },
      { source: "/service-hosting-cpanel-support", destination: "/en/services/website-development", permanent: true },
      { source: "/service-cloudflare-consultancy", destination: "/en/services/website-development", permanent: true },
      { source: "/service-branding-strategy", destination: "/en/services/branding/brand-strategy", permanent: true },
      { source: "/service-digital-branding", destination: "/en/services/branding", permanent: true },
      { source: "/service-creative", destination: "/en/services/branding", permanent: true },
      { source: "/service-logo-design", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-company-profile-design", destination: "/en/services/branding/brand-guidelines", permanent: true },
      { source: "/service-product-packaging-design", destination: "/en/services/branding/packaging-design", permanent: true },
      { source: "/service-graphic-design", destination: "/en/services/branding", permanent: true },
      { source: "/service-flyer-and-standee-design", destination: "/en/services/branding", permanent: true },
      { source: "/service-flyer-standee-design", destination: "/en/services/branding", permanent: true },
      { source: "/service-visiting-card-design", destination: "/en/services/branding", permanent: true },
      { source: "/service-t-shirt-design", destination: "/en/services/branding", permanent: true },
      { source: "/service-abstract-mark-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-dynamic-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-emblem-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-emblematic-letter-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-lettermark-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-mascot-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-minimalist-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-pictorial-mark-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-symbol-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-wordmark-logo-designs", destination: "/en/services/branding/logo-design", permanent: true },
      { source: "/service-video-production", destination: "/en/services/video-production", permanent: true },
      { source: "/service-video-editing", destination: "/en/services/video-production/video-editing", permanent: true },
      { source: "/service-reel-edit", destination: "/en/services/video-production/reels-short-form", permanent: true },
      { source: "/service-reel-production", destination: "/en/services/video-production/reels-short-form", permanent: true },
      { source: "/service-post-production", destination: "/en/services/video-production/video-editing", permanent: true },
      { source: "/service-podcast-editing", destination: "/en/services/video-production", permanent: true },
      { source: "/service-logo-animation", destination: "/en/services/video-production/animation", permanent: true },
      { source: "/service-logo-video-animation", destination: "/en/services/video-production/animation", permanent: true },
      { source: "/service-voiceover-video-integration", destination: "/en/services/video-production", permanent: true },
      { source: "/service-youtube-channel-optimization", destination: "/en/services/social-media", permanent: true },
      { source: "/service-youtube-thumbnail-design", destination: "/en/services/social-media/content-creation", permanent: true },
      { source: "/service-bpo-business-process-outsourcing", destination: "/en/services/bpo", permanent: true },
      { source: "/service-business-process-outsourcing", destination: "/en/services/bpo", permanent: true },
      { source: "/service-call-center", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-call-center-outsource", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-call-center-setup", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-call-center-software-rental", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-call-center-support", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-customer-support", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-email-support", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-general-support", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-live-chat-support", destination: "/en/services/bpo/customer-support", permanent: true },
      { source: "/service-robo-calls", destination: "/en/services/bpo", permanent: true },
      { source: "/service-manpower-outsourcing-recruitment", destination: "/en/services/bpo/operations", permanent: true },
      { source: "/service-payroll-outsourcing", destination: "/en/services/bpo/operations", permanent: true },
      { source: "/service-employee-training-development", destination: "/en/services/bpo/operations", permanent: true },
      { source: "/service-customize_filters", destination: "/en/services/social-media", permanent: true },

      // === Old /Markit/* paths (previous Next.js version) ===
      { source: "/Markit/ai", destination: "/en/services/ai", permanent: true },
      { source: "/Markit/seo", destination: "/en/services/seo", permanent: true },
      { source: "/Markit/bpo", destination: "/en/services/bpo", permanent: true },
      { source: "/Markit/blog", destination: "/en/blog", permanent: true },
      { source: "/Markit/blog/:path*", destination: "/en/blog", permanent: true },
      { source: "/Markit/creative-branding", destination: "/en/services/branding", permanent: true },
      { source: "/Markit/digital-marketing", destination: "/en/services/digital-marketing", permanent: true },
      { source: "/Markit/digital-marketing/ppc", destination: "/en/services/performance-marketing", permanent: true },
      { source: "/Markit/video-production", destination: "/en/services/video-production", permanent: true },
      { source: "/Markit/website-development", destination: "/en/services/website-development", permanent: true },
      { source: "/Markit/website-development/:path*", destination: "/en/services/website-development", permanent: true },

      // === Old /services/ai/* paths (different sub-service structure) ===
      { source: "/services/ai/ai-agent-development", destination: "/en/services/ai", permanent: true },
      { source: "/services/ai/ai-and-gpt-integration", destination: "/en/services/ai", permanent: true },
      { source: "/services/ai/ai-consulting", destination: "/en/services/ai/consulting", permanent: true },
      { source: "/services/ai/ai-digital-marketing", destination: "/en/services/ai/marketing-automation", permanent: true },
      { source: "/services/ai/chatgpt-optimization", destination: "/en/services/ai", permanent: true },
      { source: "/services/dummy", destination: "/en/services", permanent: true },

      // === Service shorthand URLs ===
      { source: "/seo-services", destination: "/en/services/seo", permanent: true },
      { source: "/ppc-advertising", destination: "/en/services/paid-advertising", permanent: true },
      { source: "/ppc-management", destination: "/en/services/performance-marketing/ppc-management", permanent: true },
      { source: "/ppc-services", destination: "/en/services/performance-marketing", permanent: true },
      { source: "/social-media-marketing", destination: "/en/services/social-media", permanent: true },
      { source: "/social-media-services", destination: "/en/services/social-media", permanent: true },
      { source: "/social-media-agency", destination: "/en/services/social-media", permanent: true },
      { source: "/web-development", destination: "/en/services/website-development", permanent: true },
      { source: "/web-development-services", destination: "/en/services/website-development", permanent: true },
      { source: "/web-design", destination: "/en/services/website-development", permanent: true },
      { source: "/web-design-agency", destination: "/en/services/website-development", permanent: true },
      { source: "/digital-marketing", destination: "/en/services/digital-marketing", permanent: true },
      { source: "/digital-marketing-agency", destination: "/en/services/digital-marketing", permanent: true },
      { source: "/digital-marketing-services", destination: "/en/services/digital-marketing", permanent: true },
      { source: "/google-ads", destination: "/en/services/performance-marketing/google-ads", permanent: true },
      { source: "/google-ads-management", destination: "/en/services/performance-marketing/google-ads", permanent: true },
      { source: "/facebook-ads", destination: "/en/services/performance-marketing/meta-ads", permanent: true },
      { source: "/facebook-ads-management", destination: "/en/services/performance-marketing/meta-ads", permanent: true },
      { source: "/instagram-marketing", destination: "/en/services/social-media", permanent: true },
      { source: "/linkedin-marketing", destination: "/en/services/performance-marketing/linkedin-ads", permanent: true },
      { source: "/youtube-marketing", destination: "/en/services/social-media", permanent: true },
      { source: "/tiktok-marketing", destination: "/en/services/performance-marketing/tiktok-ads", permanent: true },
      { source: "/email-marketing-services", destination: "/en/services/email-marketing", permanent: true },
      { source: "/branding", destination: "/en/services/branding", permanent: true },
      { source: "/branding-agency", destination: "/en/services/branding", permanent: true },
      { source: "/branding-services", destination: "/en/services/branding", permanent: true },
      { source: "/marketing-agency", destination: "/en/services", permanent: true },
      { source: "/seo-company", destination: "/en/services/seo", permanent: true },
      { source: "/content-marketing", destination: "/en/services/content-marketing", permanent: true },
      { source: "/content-writing", destination: "/en/services/content-marketing/copywriting", permanent: true },
      { source: "/email-marketing", destination: "/en/services/email-marketing", permanent: true },
      { source: "/video-production", destination: "/en/services/video-production", permanent: true },
      { source: "/video-editing", destination: "/en/services/video-production/video-editing", permanent: true },
      { source: "/ecommerce", destination: "/en/services/ecommerce-marketing", permanent: true },
      { source: "/photography", destination: "/en/services/photography", permanent: true },
      { source: "/public-relations", destination: "/en/services/public-relations", permanent: true },
      { source: "/graphic-design", destination: "/en/services/branding", permanent: true },
      { source: "/logo-design", destination: "/en/services/branding/logo-design", permanent: true },

      // === Old industry pages → actual industry pages ===
      { source: "/auto-parts-online-digital-marketing-agency", destination: "/en/industries/automotive", permanent: true },
      { source: "/b2b-services-online-digital-marketing-agency", destination: "/en/industries/b2b", permanent: true },
      { source: "/beauty-cosmetics-online-digital-marketing-agency", destination: "/en/industries/fashion", permanent: true },
      { source: "/celebrities-online-digital-marketing-agency", destination: "/en/services", permanent: true },
      { source: "/clothing-brands-online-digital-marketing-agency", destination: "/en/industries/fashion", permanent: true },
      { source: "/education-online-digital-marketing-agency", destination: "/en/industries/education", permanent: true },
      { source: "/entertainment-media-online-digital-marketing-agency", destination: "/en/services", permanent: true },
      { source: "/financial-services-online-digital-marketing-agency", destination: "/en/industries/finance", permanent: true },
      { source: "/financial-technology-fintech-online-digital-marketing-agency", destination: "/en/industries/finance", permanent: true },
      { source: "/food-brands-online-digital-marketing-agency", destination: "/en/industries/restaurants", permanent: true },
      { source: "/home-decor-interior-design-online-digital-marketing-agency", destination: "/en/industries/home-services", permanent: true },
      { source: "/kitchen-home-appliances-online-digital-marketing-agency", destination: "/en/industries/ecommerce", permanent: true },
      { source: "/medical-health-online-digital-marketing-agency", destination: "/en/industries/healthcare", permanent: true },
      { source: "/non-profit-organizations-online-digital-marketing-agency", destination: "/en/industries/nonprofits", permanent: true },
      { source: "/political-members-online-digital-marketing-agency", destination: "/en/services", permanent: true },
      { source: "/public-relations-online-digital-marketing-agency", destination: "/en/services/public-relations", permanent: true },
      { source: "/real-estate-online-digital-marketing-agency", destination: "/en/industries/real-estate", permanent: true },
      { source: "/restaurant-online-digital-marketing-agency", destination: "/en/industries/restaurants", permanent: true },
      { source: "/sports-fitness-online-digital-marketing-agency", destination: "/en/industries/fitness", permanent: true },
      { source: "/technology-gadgets-online-digital-marketing-agency", destination: "/en/industries/saas", permanent: true },
      { source: "/travel-hospitality-online-digital-marketing-agency", destination: "/en/industries/travel", permanent: true },

      // === Old city shorthand URLs ===
      { source: "/new-york", destination: "/en/locations/united-states/new-york", permanent: true },
      { source: "/los-angeles", destination: "/en/locations/united-states/los-angeles", permanent: true },
      { source: "/chicago", destination: "/en/locations/united-states/chicago", permanent: true },
      { source: "/miami", destination: "/en/locations/united-states/miami", permanent: true },
      { source: "/houston", destination: "/en/locations/united-states/houston", permanent: true },
      { source: "/san-francisco", destination: "/en/locations/united-states/san-francisco", permanent: true },
      { source: "/dallas", destination: "/en/locations/united-states/dallas", permanent: true },
      { source: "/atlanta", destination: "/en/locations/united-states/atlanta", permanent: true },

      // === Portfolio/case study redirects ===
      { source: "/portfolio/:slug", destination: "/en/work", permanent: true },
      { source: "/portfolio_tag/:slug", destination: "/en/work", permanent: true },
      { source: "/case-study/:slug", destination: "/en/work", permanent: true },

      // === WordPress taxonomy/feed/archive patterns ===
      { source: "/category/:slug", destination: "/en/blog", permanent: true },
      { source: "/tag/:slug", destination: "/en/blog", permanent: true },
      { source: "/author/:slug", destination: "/en/blog", permanent: true },
      { source: "/feed", destination: "/feed.xml", permanent: true },
      { source: "/rss", destination: "/feed.xml", permanent: true },
      { source: "/feed/:path*", destination: "/feed.xml", permanent: true },
      { source: "/blogs/page/:num", destination: "/en/blog", permanent: true },
      { source: "/blogs/:slug", destination: "/en/blog", permanent: true },
      { source: "/:year(\\d{4})/:month(\\d{2})", destination: "/en/blog", permanent: true },

      // === WordPress infrastructure ===
      { source: "/wp-content/:path*", destination: "/en", permanent: false },
      { source: "/wp-admin/:path*", destination: "/en", permanent: false },
      { source: "/wp-login.php", destination: "/en", permanent: false },
      { source: "/wp-includes/:path*", destination: "/en", permanent: false },
      { source: "/wp-json/:path*", destination: "/en", permanent: false },
      { source: "/xmlrpc.php", destination: "/en", permanent: false },
      { source: "/wp-cron.php", destination: "/en", permanent: false },
      { source: "/wp-sitemap.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/wp-sitemap-posts-post-1.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/wp-sitemap-posts-page-1.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/wp-sitemap-taxonomies-category-1.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/wp-sitemap-users-1.xml", destination: "/sitemap.xml", permanent: true },
    ];
  },
};

export default nextConfig;
