"use client";

import { useState } from "react";
import Link from "next/link";
import { JsonLd } from "@/components/json-ld";
import { ToolCTA } from "@/components/tool-cta";

interface CompetitorAd {
  id: string;
  competitor: string;
  platform: string;
  adType: string;
  headline: string;
  bodyCopy: string;
  cta: string;
  offer: string;
  landingPageUrl: string;
  targetAudience: string;
  tone: string;
  strength: string;
  weakness: string;
}

const platforms = ["Google Ads", "Meta (Facebook/Instagram)", "LinkedIn", "TikTok", "YouTube", "Twitter/X", "Display/Programmatic", "Other"];
const adTypes = ["Search Ad", "Image Ad", "Video Ad", "Carousel", "Story/Reel", "Sponsored Content", "Shopping Ad", "Other"];
const tones = ["Professional", "Casual", "Urgent", "Inspirational", "Humorous", "Educational", "Emotional", "Bold"];

let nextId = 1;

function emptyAd(): CompetitorAd {
  return {
    id: String(nextId++),
    competitor: "",
    platform: "",
    adType: "",
    headline: "",
    bodyCopy: "",
    cta: "",
    offer: "",
    landingPageUrl: "",
    targetAudience: "",
    tone: "",
    strength: "",
    weakness: "",
  };
}



export default function CompetitorAdSpyPage() {
  const [ads, setAds] = useState<CompetitorAd[]>([emptyAd()]);
  const [activeTab, setActiveTab] = useState(0);
  const [showAnalysis, setShowAnalysis] = useState(false);

  const updateAd = (index: number, field: keyof CompetitorAd, value: string) => {
    setAds((prev) => prev.map((a, i) => (i === index ? { ...a, [field]: value } : a)));
  };

  const addAd = () => {
    setAds((prev) => [...prev, emptyAd()]);
    setActiveTab(ads.length);
  };

  const removeAd = (index: number) => {
    if (ads.length <= 1) return;
    setAds((prev) => prev.filter((_, i) => i !== index));
    setActiveTab(Math.min(activeTab, ads.length - 2));
  };

  const competitors = [...new Set(ads.map((a) => a.competitor).filter(Boolean))];
  const platformBreakdown = platforms
    .map((p) => ({ name: p, count: ads.filter((a) => a.platform === p).length }))
    .filter((p) => p.count > 0)
    .sort((a, b) => b.count - a.count);
  const toneBreakdown = tones
    .map((t) => ({ name: t, count: ads.filter((a) => a.tone === t).length }))
    .filter((t) => t.count > 0)
    .sort((a, b) => b.count - a.count);

  const downloadReport = () => {
    const lines = [
      "COMPETITOR AD ANALYSIS REPORT",
      "=============================",
      "",
      `Total Ads Documented: ${ads.length}`,
      `Competitors: ${competitors.join(", ") || "None specified"}`,
      "",
    ];
    ads.forEach((ad, i) => {
      lines.push(`--- Ad #${i + 1} ---`);
      lines.push(`Competitor: ${ad.competitor || "N/A"}`);
      lines.push(`Platform: ${ad.platform || "N/A"}`);
      lines.push(`Type: ${ad.adType || "N/A"}`);
      lines.push(`Headline: ${ad.headline || "N/A"}`);
      lines.push(`Body: ${ad.bodyCopy || "N/A"}`);
      lines.push(`CTA: ${ad.cta || "N/A"}`);
      lines.push(`Offer: ${ad.offer || "N/A"}`);
      lines.push(`Landing Page: ${ad.landingPageUrl || "N/A"}`);
      lines.push(`Target Audience: ${ad.targetAudience || "N/A"}`);
      lines.push(`Tone: ${ad.tone || "N/A"}`);
      lines.push(`Strength: ${ad.strength || "N/A"}`);
      lines.push(`Weakness: ${ad.weakness || "N/A"}`);
      lines.push("");
    });
    lines.push("--- PATTERNS ---");
    lines.push(`Platforms used: ${platformBreakdown.map((p) => `${p.name} (${p.count})`).join(", ")}`);
    lines.push(`Tones used: ${toneBreakdown.map((t) => `${t.name} (${t.count})`).join(", ")}`);
    lines.push("");
    lines.push("--- Generated by Markit Media (themarkitmedia.com) ---");

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "competitor-ad-analysis.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const ad = ads[activeTab];

  return (
    <article className="px-6 lg:px-12 py-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "Competitor Ad Spy Worksheet",
          description: "Document and analyse competitor advertising across platforms. Track messaging, offers, CTAs, and creative strategies in a structured format.",
          url: "https://themarkitmedia.com/en/resources/competitor-ad-spy",
          applicationCategory: "Advertising Tool",
          operatingSystem: "Web",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          provider: { "@type": "Organization", name: "Markit Media", url: "https://themarkitmedia.com" },
        }) }}
      />
      <title>Competitor Ad Spy Worksheet | Free Marketing Tool — Markit Media</title>
      <meta name="description" content="Document and analyse competitor advertising across platforms. Track messaging, offers, CTAs, and creative strategies in a structured format." />
      <div className="max-w-5xl mx-auto">
        <nav aria-label="Breadcrumb" className="text-base text-gray-400 mb-8">
          <Link href="/resources" className="hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Resources</Link>
          <span className="mx-2">/</span>
          <span className="text-black">Competitor Ad Spy Worksheet</span>
        </nav>

        <header className="mb-12">
          <p className="text-base font-semibold tracking-widest uppercase text-gray-400 mb-3">Free Research Tool</p>
          <h1 className="font-[family-name:var(--font-display)] text-[clamp(2rem,5vw,3.5rem)] font-extrabold text-black tracking-tight leading-[1.1]">
            Competitor Ad Spy Worksheet
          </h1>
          <p className="text-lg text-gray-500 mt-4 max-w-2xl">
            Document competitor ads across platforms. Identify patterns in messaging, offers, and creative strategies to inform your own campaigns.
          </p>
        </header>

        {!showAnalysis ? (
          <div className="space-y-6">
            <div className="flex flex-wrap items-center gap-2 border-b border-gray-200 pb-3">
              {ads.map((a, i) => (
                <button
                  key={a.id}
                  onClick={() => setActiveTab(i)}
                  className={`px-4 py-2 text-base font-medium border transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2 ${
                    activeTab === i ? "bg-black text-white border-black" : "border-gray-300 text-gray-700 hover:border-black"
                  }`}
                >
                  Ad {i + 1}{a.competitor ? `: ${a.competitor}` : ""}
                </button>
              ))}
              <button onClick={addAd} className="px-4 py-2 text-base font-medium border border-dashed border-gray-300 text-gray-500 hover:border-black hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">
                + Add Ad
              </button>
            </div>

            {ad && (
              <section aria-label="Content section" className="border border-gray-200 p-6 lg:p-8 space-y-5">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Competitor Name</label>
                    <input type="text" value={ad.competitor} onChange={(e) => updateAd(activeTab, "competitor", e.target.value)} placeholder="e.g. Acme Marketing" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                  </div>
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Platform</label>
                    <select value={ad.platform} onChange={(e) => updateAd(activeTab, "platform", e.target.value)} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black bg-white">
                      <option value="">Select</option>
                      {platforms.map((p) => <option key={p} value={p}>{p}</option>)}
                    </select>
                  </div>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Ad Type</label>
                    <select value={ad.adType} onChange={(e) => updateAd(activeTab, "adType", e.target.value)} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black bg-white">
                      <option value="">Select</option>
                      {adTypes.map((t) => <option key={t} value={t}>{t}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Tone</label>
                    <select value={ad.tone} onChange={(e) => updateAd(activeTab, "tone", e.target.value)} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black bg-white">
                      <option value="">Select</option>
                      {tones.map((t) => <option key={t} value={t}>{t}</option>)}
                    </select>
                  </div>
                </div>
                <div>
                  <label className="block text-base font-bold text-black mb-2">Headline / Hook</label>
                  <input type="text" value={ad.headline} onChange={(e) => updateAd(activeTab, "headline", e.target.value)} placeholder="What's the main headline or hook?" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                </div>
                <div>
                  <label className="block text-base font-bold text-black mb-2">Body Copy / Description</label>
                  <textarea value={ad.bodyCopy} onChange={(e) => updateAd(activeTab, "bodyCopy", e.target.value)} placeholder="Key messaging points" rows={3} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black resize-y" />
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Call to Action</label>
                    <input type="text" value={ad.cta} onChange={(e) => updateAd(activeTab, "cta", e.target.value)} placeholder="e.g. Get Started Free" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                  </div>
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Offer / Incentive</label>
                    <input type="text" value={ad.offer} onChange={(e) => updateAd(activeTab, "offer", e.target.value)} placeholder="e.g. 20% off first month" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                  </div>
                </div>
                <div>
                  <label className="block text-base font-bold text-black mb-2">Target Audience (estimated)</label>
                  <input type="text" value={ad.targetAudience} onChange={(e) => updateAd(activeTab, "targetAudience", e.target.value)} placeholder="Who are they targeting?" className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black" />
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Strength</label>
                    <textarea value={ad.strength} onChange={(e) => updateAd(activeTab, "strength", e.target.value)} placeholder="What's this ad doing well?" rows={2} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black resize-y" />
                  </div>
                  <div>
                    <label className="block text-base font-bold text-black mb-2">Weakness / Opportunity</label>
                    <textarea value={ad.weakness} onChange={(e) => updateAd(activeTab, "weakness", e.target.value)} placeholder="Where could you do better?" rows={2} className="w-full border border-gray-300 px-4 py-3 text-base focus-visible:outline-none focus-visible:border-black resize-y" />
                  </div>
                </div>
                {ads.length > 1 && (
                  <button onClick={() => removeAd(activeTab)} className="text-base text-gray-400 hover:text-red-600 transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">
                    Remove this ad
                  </button>
                )}
              </section>
            )}

            <div className="flex flex-wrap gap-4">
              <button
                onClick={() => setShowAnalysis(true)}
                disabled={!ads.some((a) => a.competitor && a.platform)}
                className="bg-black text-white px-8 py-4 text-base font-bold hover:bg-gray-800 transition-colors disabled:opacity-40 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2"
              >
                View Analysis &rarr;
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-8">
            <section aria-label="Overview" className="border border-gray-200 p-6 lg:p-8">
              <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-black mb-6">Overview</h2>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
                <div className="border border-gray-200 p-4">
                  <div className="text-3xl font-extrabold text-black">{ads.length}</div>
                  <div className="text-base text-gray-500">Ads Documented</div>
                </div>
                <div className="border border-gray-200 p-4">
                  <div className="text-3xl font-extrabold text-black">{competitors.length}</div>
                  <div className="text-base text-gray-500">Competitors</div>
                </div>
                <div className="border border-gray-200 p-4">
                  <div className="text-3xl font-extrabold text-black">{platformBreakdown.length}</div>
                  <div className="text-base text-gray-500">Platforms</div>
                </div>
                <div className="border border-gray-200 p-4">
                  <div className="text-3xl font-extrabold text-black">{toneBreakdown.length}</div>
                  <div className="text-base text-gray-500">Tone Styles</div>
                </div>
              </div>
            </section>

            {platformBreakdown.length > 0 && (
              <section aria-label="Platform Distribution" className="border border-gray-200 p-6 lg:p-8">
                <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-black mb-4">Platform Distribution</h2>
                <div className="space-y-3">
                  {platformBreakdown.map((p) => (
                    <div key={p.name} className="flex items-center gap-4">
                      <span className="w-48 text-base text-gray-700 shrink-0">{p.name}</span>
                      <div className="flex-1 h-6 bg-gray-100">
                        <div className="h-6 bg-black transition-all" style={{ width: `${(p.count / ads.length) * 100}%` }} />
                      </div>
                      <span className="text-base font-bold text-black w-8 text-right">{p.count}</span>
                    </div>
                  ))}
                </div>
              </section>
            )}

            <section aria-label="Ad Details" className="border border-gray-200 p-6 lg:p-8">
              <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-black mb-4">Ad Details</h2>
              <div className="space-y-4">
                {ads.map((a, i) => (
                  <div key={a.id} className="border border-gray-100 p-4">
                    <div className="flex items-center justify-between mb-2">
                      <h3 className="text-base font-bold text-black">{a.competitor || `Ad ${i + 1}`}</h3>
                      <div className="flex gap-2">
                        {a.platform && <span className="bg-gray-100 text-gray-700 px-2 py-1 text-base">{a.platform}</span>}
                        {a.tone && <span className="bg-gray-100 text-gray-700 px-2 py-1 text-base">{a.tone}</span>}
                      </div>
                    </div>
                    {a.headline && <p className="text-base text-black font-medium mb-1">&ldquo;{a.headline}&rdquo;</p>}
                    {a.cta && <p className="text-base text-gray-600">CTA: {a.cta}</p>}
                    {a.offer && <p className="text-base text-gray-600">Offer: {a.offer}</p>}
                    {a.strength && <p className="text-base text-gray-600"><span className="text-green-700 font-medium">Strength:</span> {a.strength}</p>}
                    {a.weakness && <p className="text-base text-gray-600"><span className="text-red-700 font-medium">Opportunity:</span> {a.weakness}</p>}
                  </div>
                ))}
              </div>
            </section>

            <div className="flex flex-wrap gap-4">
              <button onClick={downloadReport} className="bg-black text-white px-8 py-3 text-base font-bold hover:bg-gray-800 transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">
                Download Report (.txt)
              </button>
              <button onClick={() => setShowAnalysis(false)} className="border border-gray-300 text-gray-700 px-6 py-3 text-base font-medium hover:border-black hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">
                Edit Worksheet
              </button>
            </div>

            <section aria-label="Want to Outperform Your Competitors?" className="bg-black text-white p-8 lg:p-12 text-center">
              <h2 className="font-[family-name:var(--font-display)] text-2xl font-extrabold mb-4">Want to Outperform Your Competitors?</h2>
              <p className="text-lg text-gray-300 mb-8 max-w-xl mx-auto">Our team analyses competitor strategies and builds campaigns designed to win market share.</p>
              <Link href="/contact" className="inline-block bg-white text-black px-10 py-5 text-base font-bold hover:bg-gray-100 transition-colors focus-visible:outline-2 focus-visible:outline-white focus-visible:outline-offset-2">
                Get a Competitive Analysis &rarr;
              </Link>
            </section>
          </div>
        )}
      </div>
          
      {/* Related Tools */}
      <section className="px-6 lg:px-12 py-12" aria-label="Related tools">
        <div className="max-w-4xl mx-auto">
          <h2 className="font-[family-name:var(--font-display)] text-lg font-extrabold text-black mb-4">Related Tools</h2>
          <div className="flex flex-wrap gap-3">
                <Link href="/resources/competitor-analysis" className="border border-neutral-200 px-4 py-2 text-base font-medium text-black hover:bg-black hover:text-white transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Competitor Analysis</Link>
                <Link href="/resources/competitor-benchmarking" className="border border-neutral-200 px-4 py-2 text-base font-medium text-black hover:bg-black hover:text-white transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Competitor Benchmarking</Link>
                <Link href="/resources/competitor-matrix" className="border border-neutral-200 px-4 py-2 text-base font-medium text-black hover:bg-black hover:text-white transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Competitor Matrix</Link>
                <Link href="/resources/competitor-pricing-tracker" className="border border-neutral-200 px-4 py-2 text-base font-medium text-black hover:bg-black hover:text-white transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Competitor Pricing</Link>
          </div>
        </div>
      </section>
<JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "Competitor Ad Spy Worksheet",
          description: "Document and analyse competitor advertising across platforms. Track messaging, offers, CTAs, and creative strategies in a structured format.",
          applicationCategory: "MarketingApplication",
          operatingSystem: "Any",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        }}
      />
    
      <ToolCTA
        toolName="Competitor Ad Spy"
        services={[
          { title: "Digital Marketing", desc: "Competitive intelligence turned into actionable growth strategy.", href: "/services/digital-marketing" },
          { title: "SEO", desc: "Outrank competitors with data-backed SEO strategies.", href: "/services/seo" },
          { title: "Performance Marketing", desc: "Win market share with smarter paid media campaigns.", href: "/services/performance-marketing" },
        ]}
        relatedTools={[
          { title: "Competitive Swot", href: "/resources/competitive-swot" },
          { title: "Competitive Swot Analyzer", href: "/resources/competitive-swot-analyzer" },
          { title: "Competitor Analysis", href: "/resources/competitor-analysis" },
          { title: "Competitor Benchmarking", href: "/resources/competitor-benchmarking" },
        ]}
        relatedBlog={[
          { title: "Digital Marketing Strategy Guide", href: "/blog" },
          { title: "How to Measure Marketing ROI", href: "/blog" },
        ]}
      />
    </article>
  );
}
