"use client";

import { useState } from "react";
import Link from "next/link";

interface ToolEntry {
  name: string;
  status: "active" | "underused" | "not-using" | "";
  satisfaction: number;
  notes: string;
}

interface StackCategory {
  name: string;
  description: string;
  tools: string[];
}

const categories: StackCategory[] = [
  {
    name: "Analytics & Tracking",
    description: "Tools for measuring website and marketing performance",
    tools: ["Google Analytics 4", "Google Tag Manager", "Hotjar / Clarity", "Mixpanel / Amplitude", "Google Search Console"],
  },
  {
    name: "CRM & Sales",
    description: "Customer relationship management and sales tools",
    tools: ["HubSpot CRM", "Salesforce", "Pipedrive", "Zoho CRM", "Custom / Other CRM"],
  },
  {
    name: "Email Marketing",
    description: "Email automation, campaigns, and list management",
    tools: ["Mailchimp", "Klaviyo", "ActiveCampaign", "HubSpot Email", "ConvertKit / Beehiiv"],
  },
  {
    name: "Advertising",
    description: "Paid media and advertising platforms",
    tools: ["Google Ads", "Meta Ads Manager", "LinkedIn Ads", "TikTok Ads", "Programmatic / DSP"],
  },
  {
    name: "Social Media",
    description: "Social publishing, scheduling, and monitoring",
    tools: ["Hootsuite / Sprout Social", "Buffer / Later", "Native Platform Tools", "Social Listening Tool", "Influencer Platform"],
  },
  {
    name: "Content & SEO",
    description: "Content creation, management, and search optimisation",
    tools: ["WordPress / CMS", "SEMrush / Ahrefs", "Canva / Adobe Creative", "AI Writing Tools", "Project Management (Asana/Monday)"],
  },
];

function getStatusColor(status: string): string {
  if (status === "active") return "bg-green-100 text-green-800";
  if (status === "underused") return "bg-yellow-100 text-yellow-800";
  if (status === "not-using") return "bg-gray-100 text-gray-500";
  return "bg-white text-gray-400";
}

export default function MarketingStackAuditPage() {
  const [entries, setEntries] = useState<Record<string, ToolEntry>>(() => {
    const init: Record<string, ToolEntry> = {};
    categories.forEach((cat) =>
      cat.tools.forEach((tool) => {
        init[`${cat.name}::${tool}`] = { name: tool, status: "", satisfaction: 0, notes: "" };
      })
    );
    return init;
  });
  const [showResults, setShowResults] = useState(false);

  const updateEntry = (key: string, field: keyof ToolEntry, value: string | number) => {
    setEntries((prev) => ({ ...prev, [key]: { ...prev[key], [field]: value } }));
  };

  const activeTools = Object.values(entries).filter((e) => e.status === "active").length;
  const underusedTools = Object.values(entries).filter((e) => e.status === "underused").length;
  const gaps = Object.values(entries).filter((e) => e.status === "not-using").length;
  const totalAssessed = activeTools + underusedTools + gaps;

  const catSummaries = categories.map((cat) => {
    const catEntries = cat.tools.map((t) => entries[`${cat.name}::${t}`]);
    const active = catEntries.filter((e) => e.status === "active").length;
    const underused = catEntries.filter((e) => e.status === "underused").length;
    const avgSat = catEntries.filter((e) => e.satisfaction > 0).reduce((sum, e, _, arr) => sum + e.satisfaction / arr.length, 0);
    return { name: cat.name, active, underused, total: cat.tools.length, avgSat: Math.round(avgSat * 10) / 10 };
  });

  const downloadAudit = () => {
    const lines = [
      "MARKETING STACK AUDIT REPORT",
      "============================",
      "",
      `Active Tools: ${activeTools}`,
      `Underused Tools: ${underusedTools}`,
      `Gaps (Not Using): ${gaps}`,
      "",
    ];
    categories.forEach((cat) => {
      lines.push(`--- ${cat.name} ---`);
      cat.tools.forEach((tool) => {
        const e = entries[`${cat.name}::${tool}`];
        if (e.status) {
          lines.push(`  ${tool}: ${e.status}${e.satisfaction ? ` (${e.satisfaction}/5)` : ""}${e.notes ? ` - ${e.notes}` : ""}`);
        }
      });
      lines.push("");
    });
    lines.push("--- Generated by Markit Media (themarkitmedia.com) ---");
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "marketing-stack-audit.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <article className="px-6 lg:px-12 py-16">
      <div className="max-w-5xl mx-auto">
        <nav aria-label="Breadcrumb" className="text-base text-gray-400 mb-8">
          <Link href="/resources" className="hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Resources</Link>
          <span className="mx-2">/</span>
          <span className="text-black">Marketing Stack Audit</span>
        </nav>

        <header className="mb-12">
          <p className="text-base font-semibold tracking-widest uppercase text-gray-400 mb-3">Free Assessment Tool</p>
          <h1 className="font-[family-name:var(--font-display)] text-[clamp(2rem,5vw,3.5rem)] font-extrabold text-black tracking-tight leading-[1.1]">
            Marketing Stack Audit
          </h1>
          <p className="text-lg text-gray-500 mt-4 max-w-2xl">
            Audit your marketing technology stack across 6 categories. Identify active tools, underused investments, and coverage gaps.
          </p>
        </header>

        {!showResults ? (
          <div className="space-y-8">
            {categories.map((cat) => (
              <section key={cat.name} className="border border-gray-200 p-6 lg:p-8">
                <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-black mb-1">{cat.name}</h2>
                <p className="text-base text-gray-500 mb-6">{cat.description}</p>
                <div className="space-y-4">
                  {cat.tools.map((tool) => {
                    const key = `${cat.name}::${tool}`;
                    const entry = entries[key];
                    return (
                      <div key={key} className="flex flex-col sm:flex-row sm:items-center gap-3 pb-3 border-b border-gray-100 last:border-0">
                        <span className="text-base font-medium text-black w-52 shrink-0">{tool}</span>
                        <select
                          value={entry.status}
                          onChange={(e) => updateEntry(key, "status", e.target.value)}
                          className={`border border-gray-300 px-3 py-2 text-base focus-visible:outline-none focus-visible:border-black ${getStatusColor(entry.status)}`}
                        >
                          <option value="">Not assessed</option>
                          <option value="active">Active</option>
                          <option value="underused">Underused</option>
                          <option value="not-using">Not Using</option>
                        </select>
                        {entry.status && entry.status !== "not-using" && (
                          <div className="flex items-center gap-1">
                            {[1, 2, 3, 4, 5].map((n) => (
                              <button
                                key={n}
                                onClick={() => updateEntry(key, "satisfaction", n)}
                                className={`w-8 h-8 border text-base font-medium transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2 ${
                                  entry.satisfaction >= n ? "bg-black text-white border-black" : "border-gray-300 text-gray-400 hover:border-black"
                                }`}
                              >
                                {n}
                              </button>
                            ))}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </section>
            ))}

            <button onClick={() => setShowResults(true)} disabled={totalAssessed === 0} className="bg-black text-white px-8 py-4 text-base font-bold hover:bg-gray-800 transition-colors disabled:opacity-40 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">
              View Audit Results &rarr;
            </button>
          </div>
        ) : (
          <div className="space-y-8">
            <section className="border border-gray-200 p-6 lg:p-8">
              <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-black mb-6">Stack Overview</h2>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
                <div className="border border-gray-200 p-4">
                  <div className="text-3xl font-extrabold text-black">{totalAssessed}</div>
                  <div className="text-base text-gray-500">Tools Assessed</div>
                </div>
                <div className="border border-green-200 bg-green-50 p-4">
                  <div className="text-3xl font-extrabold text-green-800">{activeTools}</div>
                  <div className="text-base text-green-700">Active</div>
                </div>
                <div className="border border-yellow-200 bg-yellow-50 p-4">
                  <div className="text-3xl font-extrabold text-yellow-800">{underusedTools}</div>
                  <div className="text-base text-yellow-700">Underused</div>
                </div>
                <div className="border border-gray-200 p-4">
                  <div className="text-3xl font-extrabold text-gray-500">{gaps}</div>
                  <div className="text-base text-gray-500">Gaps</div>
                </div>
              </div>
            </section>

            <section className="border border-gray-200 p-6 lg:p-8">
              <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-black mb-4">Category Breakdown</h2>
              <div className="space-y-4">
                {catSummaries.map((cs) => (
                  <div key={cs.name} className="flex items-center gap-4">
                    <span className="w-48 text-base text-gray-700 shrink-0 font-medium">{cs.name}</span>
                    <div className="flex-1 h-6 bg-gray-100 flex">
                      <div className="h-6 bg-green-600" style={{ width: `${(cs.active / cs.total) * 100}%` }} />
                      <div className="h-6 bg-yellow-400" style={{ width: `${(cs.underused / cs.total) * 100}%` }} />
                    </div>
                    <span className="text-base text-gray-500 w-20 text-right">{cs.active + cs.underused}/{cs.total}</span>
                  </div>
                ))}
                <div className="flex gap-4 text-base text-gray-500 mt-2">
                  <span className="flex items-center gap-1"><span className="w-3 h-3 bg-green-600 inline-block" /> Active</span>
                  <span className="flex items-center gap-1"><span className="w-3 h-3 bg-yellow-400 inline-block" /> Underused</span>
                </div>
              </div>
            </section>

            {underusedTools > 0 && (
              <section className="border border-yellow-200 bg-yellow-50 p-6 lg:p-8">
                <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-yellow-900 mb-4">Underused Tools (Optimisation Opportunities)</h2>
                <div className="space-y-2">
                  {Object.entries(entries).filter(([, e]) => e.status === "underused").map(([key, e]) => (
                    <div key={key} className="text-base text-yellow-800">
                      <span className="font-medium">{e.name}</span>
                      {e.satisfaction > 0 && <span className="text-yellow-600"> (Satisfaction: {e.satisfaction}/5)</span>}
                    </div>
                  ))}
                </div>
              </section>
            )}

            <div className="flex flex-wrap gap-4">
              <button onClick={downloadAudit} className="bg-black text-white px-8 py-3 text-base font-bold hover:bg-gray-800 transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Download Audit (.txt)</button>
              <button onClick={() => setShowResults(false)} className="border border-gray-300 text-gray-700 px-6 py-3 text-base font-medium hover:border-black hover:text-black transition-colors focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2">Edit Audit</button>
            </div>

            <section className="bg-black text-white p-8 lg:p-12 text-center">
              <h2 className="font-[family-name:var(--font-display)] text-2xl font-extrabold mb-4">Need Help Optimising Your Stack?</h2>
              <p className="text-lg text-gray-300 mb-8 max-w-xl mx-auto">We help businesses select, integrate, and optimise their marketing technology for maximum impact.</p>
              <Link href="/contact" className="inline-block bg-white text-black px-10 py-5 text-base font-bold hover:bg-gray-100 transition-colors focus-visible:outline-2 focus-visible:outline-white focus-visible:outline-offset-2">Get Stack Optimisation Help &rarr;</Link>
            </section>
          </div>
        )}
      </div>
    </article>
  );
}
