import type {Metadata} from "next";import Link from "next/link";import {CalendarDays,Check,Mail,ArrowRight} from "lucide-react";
export const metadata:Metadata={title:"Thank You | Markit Media",description:"Your request has been received by Markit Media.",robots:{index:false,follow:true}};
const CALENDLY="https://calendly.com/ureb-arif-markit-media/new-meeting";
export default function ThankYouPage(){return <main className="min-h-[82vh] bg-white px-6 py-20 lg:px-12"><div className="mx-auto max-w-5xl">
 <section className="overflow-hidden rounded-[32px] border border-black/10 bg-black text-white shadow-[0_30px_100px_rgba(0,0,0,.12)]"><div className="grid lg:grid-cols-[1.08fr_.92fr]">
  <div className="p-8 sm:p-12 lg:p-14"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-black"><Check size={26}/></div><p className="mt-8 text-xs font-extrabold uppercase tracking-[.2em] text-white/45">Request received</p><h1 className="mt-3 max-w-xl text-4xl font-black tracking-tight sm:text-5xl">Thanks. Markit Media has your brief.</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/65">Your details are safely with our team. We’ll review what you shared and follow up with the most relevant next step.</p>
  <div className="mt-8 flex items-center gap-3 text-sm text-white/60"><Mail size={17}/><span>You’ll also receive a confirmation by email.</span></div></div>
  <div className="bg-white p-8 text-black sm:p-12 lg:p-14"><div className="inline-flex items-center gap-2 rounded-full bg-[#f3f0ff] px-3 py-1.5 text-xs font-extrabold text-[#5A3ED6]"><CalendarDays size={14}/> Optional next step</div><h2 className="mt-5 text-3xl font-black tracking-tight">Want to move faster?</h2><p className="mt-3 text-sm leading-6 text-gray-500">Choose a convenient time to talk to Markit Media. You don’t need to repeat your brief — we already have it.</p><a href={CALENDLY} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-black px-6 py-4 text-sm font-extrabold text-white hover:bg-zinc-800">Schedule a Call <ArrowRight size={16}/></a><p className="mt-3 text-center text-xs text-gray-400">Prefer email? No problem. Your request is already submitted.</p></div>
 </div></section>
 <section className="mt-10 grid gap-4 md:grid-cols-3">{[["01","We review your brief","Your form details reach the team before any conversation."],["02","Talk to Markit Media","Book a call now, or wait for our email response."],["03","Get clear next steps","We’ll recommend the most relevant approach for your goals."]].map(([n,t,d])=><div key={n} className="rounded-2xl border bg-[#fafafa] p-6"><span className="text-xs font-black text-gray-300">{n}</span><h3 className="mt-3 font-extrabold">{t}</h3><p className="mt-2 text-sm leading-6 text-gray-500">{d}</p></div>)}</section>
 <div className="mt-10 text-center"><Link href="/case-studies" className="text-sm font-bold underline underline-offset-4">Explore our case studies while you wait</Link></div>
 </div></main>}