import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { saveFormSubmission } from "@/lib/mongodb";

const rateLimitMap = new Map<string, { count: number; resetTime: number }>();
function limited(ip:string){const now=Date.now(),e=rateLimitMap.get(ip);if(!e||now>e.resetTime){rateLimitMap.set(ip,{count:1,resetTime:now+60_000});return false;}e.count++;return e.count>5;}
function esc(v:unknown){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").trim();}
function serviceLabel(v:string){return v ? v.split("-").map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(" ") : "General Inquiry";}
function portfolio(v:string){const m:Record<string,string>={branding:"/work/logo-folio","video-production":"/work","social-media":"/work","website-development":"/work","performance-marketing":"/case-studies",seo:"/case-studies"};return m[v]||"/work";}
export async function POST(request:NextRequest){
 try{
  const ip=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";if(limited(ip))return NextResponse.json({error:"Too many requests. Please try again later."},{status:429});
  const body=await request.json();if(body.website)return NextResponse.json({success:true});
  const data={name:esc(body.name),email:esc(body.email),company:esc(body.company),phone:esc(body.phone),service:esc(body.service),budget:esc(body.budget),timeline:esc(body.timeline),message:esc(body.message),source:esc(body.source),landingPage:esc(body.landingPage),referrer:esc(body.referrer),utmSource:esc(body.utmSource),utmMedium:esc(body.utmMedium),utmCampaign:esc(body.utmCampaign),marketingConsent:Boolean(body.marketingConsent),submittedAt:new Date().toISOString(),status:"New"};
  if(!data.name||data.name.length<2)return NextResponse.json({error:"Name is required."},{status:400});
  if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))return NextResponse.json({error:"A valid email address is required."},{status:400});
  if(!data.message||data.message.length<5)return NextResponse.json({error:"Please enter a message."},{status:400});
  try{await saveFormSubmission("lead",{...data,internalNotes:"",assignedTo:"",updatedAt:new Date()});}catch(e){console.error("Failed to save lead to MongoDB",e);return NextResponse.json({error:"We could not save your request. Please try again."},{status:503});}
  if(!process.env.RESEND_API_KEY)return NextResponse.json({error:"We could not send your message. Please email ciao@themarkitmedia.com directly."},{status:503});
  const resend=new Resend(process.env.RESEND_API_KEY);const from=process.env.RESEND_FROM_EMAIL||"Markit Media <contact@themarkitmedia.com>";const label=serviceLabel(data.service);const isDiscovery=data.source==="Brand Discovery Brief";const messageHtml=data.message.replace(/\\n/g,"<br>");
  const internal=await resend.emails.send({from,to:["ciao@themarkitmedia.com","ureb.arif@themarkitmedia.com","urebarif@gmail.com"],replyTo:data.email,subject:isDiscovery?`New Discovery Brief: ${data.name} — ${data.company||data.name}`:`New Website Lead: ${data.name} — ${label}`,html:`<h2>${isDiscovery?"New pre-discovery brand brief":"New website inquiry"}</h2><p><b>Name:</b> ${data.name}<br><b>Email:</b> ${data.email}<br><b>Company:</b> ${data.company||"—"}<br><b>Phone/WhatsApp:</b> ${data.phone||"—"}<br><b>Service:</b> ${label}<br><b>Budget:</b> ${data.budget||"—"}<br><b>Timeline:</b> ${data.timeline||"—"}<br><b>Source:</b> ${data.source||"Website"}<br><b>Landing page:</b> ${data.landingPage||"—"}<br><b>UTM:</b> ${[data.utmSource,data.utmMedium,data.utmCampaign].filter(Boolean).join(" / ")||"—"}</p><p><b>${isDiscovery?"Discovery brief":"Message"}</b><br>${messageHtml}</p>`});
  if(internal.error)return NextResponse.json({error:"We could not send your message. Please email ciao@themarkitmedia.com directly."},{status:502});
  const customer=await resend.emails.send({from,to:[data.email],replyTo:"ciao@themarkitmedia.com",subject:isDiscovery?"Your discovery brief is with us — Markit Media":"We received your brief — Markit Media",html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#111"><h1 style="font-size:24px">Thanks, ${data.name}.</h1><p>${isDiscovery?"We’ve received your pre-discovery brand brief. Our team will review your brand, market, launch stage, and priorities before the conversation so we can focus on strategy and next steps.":`We’ve received your inquiry about <b>${label}</b>. Our team will review the details you shared and respond by email or WhatsApp within one business day.`}</p><div style="background:#f5f5f5;padding:18px;margin:24px 0"><b>${isDiscovery?"Your brief":"Your inquiry"}</b><br>${isDiscovery?`Brand: ${data.company||"—"}`:`Service: ${label}`}${data.company&&!isDiscovery?`<br>Company: ${data.company}`:""}</div><p>If there’s anything else we should know, simply reply to this email or message us on WhatsApp.</p><p><a href="https://themarkitmedia.com${portfolio(data.service)}" style="color:#111;font-weight:bold">View relevant work →</a> &nbsp; <a href="https://wa.me/923002086081" style="color:#111;font-weight:bold">WhatsApp us →</a></p><p style="margin-top:32px">Markit Media<br><a href="mailto:ciao@themarkitmedia.com">ciao@themarkitmedia.com</a></p></div>`});
  if(customer.error)console.error("Customer acknowledgement failed",customer.error);
  return NextResponse.json({success:true});
 }catch{return NextResponse.json({error:"Invalid request body."},{status:400});}
}
