import { NextRequest, NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { getMongoDb } from "@/lib/mongodb";
import { verifyToken } from "@/lib/auth";

function auth(request: NextRequest) { const t=request.cookies.get("admin_token")?.value||request.headers.get("authorization")?.replace("Bearer ","")||""; return verifyToken(t); }
const view=(x:any)=>({...x,id:x._id.toString(),_id:undefined,original_name:x.originalName,mime_type:x.mimeType,alt_text:x.altText,created_at:x.createdAt});

export async function GET(request:NextRequest){
 if(!auth(request)) return NextResponse.json({error:"Unauthorized"},{status:401});
 try{const db=await getMongoDb(),c=db.collection("media_assets"),q=new URL(request.url).searchParams,page=Math.max(1,Number(q.get("page"))||1),limit=Math.min(100,Math.max(1,Number(q.get("limit"))||30));const f:any={};if(q.get("folder"))f.folder=q.get("folder");if(q.get("search"))f.$or=[{originalName:{$regex:q.get("search"),$options:"i"}},{altText:{$regex:q.get("search"),$options:"i"}}];const [docs,total,folders]=await Promise.all([c.find(f).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).toArray(),c.countDocuments(f),c.aggregate([{$match:{folder:{$nin:["",null]}}},{$group:{_id:"$folder"}},{$sort:{_id:1}}]).toArray()]);return NextResponse.json({media:docs.map(view),total,page,limit,totalPages:Math.max(1,Math.ceil(total/limit)),folders:folders.map((x:any)=>x._id),storageReady:Boolean(process.env.R2_ENDPOINT&&process.env.R2_BUCKET_NAME&&process.env.R2_ACCESS_KEY_ID&&process.env.R2_SECRET_ACCESS_KEY),publicUrlConfigured:Boolean(process.env.R2_PUBLIC_URL)});}catch(e){console.error(e);return NextResponse.json({error:"Media database unavailable"},{status:503});}
}
export async function POST(request:NextRequest){
 const session=auth(request);if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});
 try{const b=await request.json();if(!b.url)return NextResponse.json({error:"Media URL required. R2 direct upload will activate after Cloudflare migration."},{status:400});const db=await getMongoDb(),now=new Date(),doc={filename:String(b.filename||b.original_name||"asset"),originalName:String(b.original_name||b.filename||"asset"),mimeType:String(b.mime_type||"application/octet-stream"),size:Number(b.size)||0,altText:String(b.alt_text||""),folder:String(b.folder||"general"),url:String(b.url),storage:String(b.storage||"external"),createdAt:now,updatedAt:now,createdBy:session.email};const r=await db.collection("media_assets").insertOne(doc);await db.collection("activity_log").insertOne({action:"media.created",entityType:"media_asset",entityId:r.insertedId.toString(),actor:session.email,createdAt:now});return NextResponse.json({id:r.insertedId.toString(),...view({...doc,_id:r.insertedId}),success:true},{status:201});}catch(e){console.error(e);return NextResponse.json({error:"Could not save media"},{status:500});}
}
export async function PATCH(request:NextRequest){const session=auth(request);if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});try{const b=await request.json();if(!ObjectId.isValid(String(b.id)))return NextResponse.json({error:"Valid media ID required"},{status:400});const set:any={updatedAt:new Date()};for(const [a,k] of [["alt_text","altText"],["folder","folder"],["url","url"]] as const)if(a in b)set[k]=String(b[a]);const db=await getMongoDb();await db.collection("media_assets").updateOne({_id:new ObjectId(String(b.id))},{$set:set});return NextResponse.json({success:true});}catch(e){return NextResponse.json({error:"Could not update media"},{status:500});}}
export async function DELETE(request:NextRequest){const session=auth(request);if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});try{const {id}=await request.json();if(!ObjectId.isValid(String(id)))return NextResponse.json({error:"Valid media ID required"},{status:400});const db=await getMongoDb();await db.collection("media_assets").deleteOne({_id:new ObjectId(String(id))});await db.collection("activity_log").insertOne({action:"media.deleted",entityType:"media_asset",entityId:String(id),actor:session.email,createdAt:new Date()});return NextResponse.json({success:true});}catch(e){return NextResponse.json({error:"Could not delete media"},{status:500});}}
