import Link from "next/link";
import { Animate, Stagger } from "@/components/animate";
import { SectionLabel, SectionTitle, SectionDesc } from "@/components/section";
import { Breadcrumb } from "@/components/breadcrumb";
import { JsonLd } from "@/components/json-ld";
export interface PriorityIndustryData {name:string;eyebrow:string;title:string;intro:string;keywords:string[];services:{title:string;desc:string;href:string}[];challenges:{title:string;desc:string}[];playbook:{title:string;desc:string}[];metrics:string[];faq:{q:string;a:string}[];cta:string;}
export function PriorityIndustryPage({data}:{data:PriorityIndustryData}){
 const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:data.faq.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))};
 return <article><JsonLd data={faqSchema}/><Breadcrumb items={[{label:"Home",href:"/"},{label:"Industries",href:"/industries"},{label:data.name}]}/>
 <section className="px-6 lg:px-12 pt-24 pb-20"><div className="max-w-6xl mx-auto"><Animate animation="fade-up"><SectionLabel>{data.eyebrow}</SectionLabel><h1 className="font-[family-name:var(--font-display)] text-[clamp(2.4rem,5vw,4.2rem)] font-extrabold tracking-tight leading-[1.05] mt-3">{data.title}</h1><p className="text-xl text-gray-500 leading-relaxed mt-6 max-w-4xl">{data.intro}</p></Animate><div className="flex flex-wrap gap-2 mt-8">{data.keywords.map(x=><span key={x} className="border border-gray-200 bg-gray-50 px-4 py-2 text-base font-semibold">{x}</span>)}</div><div className="flex flex-wrap gap-4 mt-9"><Link href="/get-a-quote" className="bg-black text-white px-9 py-4 font-bold">Request a Growth Plan &rarr;</Link><a href="https://wa.me/923002086081" target="_blank" rel="noopener noreferrer" className="border-2 border-black px-9 py-4 font-bold">WhatsApp Us</a></div></div></section>
 <section className="px-6 lg:px-12 py-20 bg-black text-white"><div className="max-w-7xl mx-auto"><SectionLabel><span className="text-gray-400">Niche Growth Stack</span></SectionLabel><h2 className="text-[clamp(2rem,4vw,3rem)] font-extrabold">Marketing Built Around the Buying Journey</h2><Stagger stagger={60} animation="fade-up" className="grid md:grid-cols-2 lg:grid-cols-3 gap-px bg-white/10 mt-10">{data.services.map(s=><Link key={s.title} href={s.href} className="bg-black p-7 hover:bg-white/[0.04]"><h3 className="text-lg font-extrabold">{s.title}</h3><p className="text-gray-400 leading-relaxed mt-3">{s.desc}</p><span className="inline-block mt-4 font-bold">Explore service &rarr;</span></Link>)}</Stagger></div></section>
 <section className="px-6 lg:px-12 py-20"><div className="max-w-7xl mx-auto"><SectionLabel>What We Solve</SectionLabel><SectionTitle>Where Generic Marketing Breaks Down</SectionTitle><SectionDesc>Different niches have different search intent, trust barriers, economics, compliance considerations, creative needs, and sales cycles.</SectionDesc><Stagger stagger={60} animation="fade-up" className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mt-10">{data.challenges.map((x,i)=><div key={x.title} className="border border-gray-200 p-7"><span className="text-gray-300 font-bold">0{i+1}</span><h3 className="text-lg font-extrabold mt-4">{x.title}</h3><p className="text-gray-500 leading-relaxed mt-3">{x.desc}</p></div>)}</Stagger></div></section>
 <section className="px-6 lg:px-12 py-20 bg-gray-50"><div className="max-w-7xl mx-auto"><SectionLabel>Playbook</SectionLabel><SectionTitle>How We Build the Growth System</SectionTitle><div className="grid md:grid-cols-2 gap-6 mt-10">{data.playbook.map(x=><div key={x.title} className="bg-white border-t-4 border-black p-7"><h3 className="text-xl font-extrabold">{x.title}</h3><p className="text-gray-500 leading-relaxed mt-3">{x.desc}</p></div>)}</div></div></section>
 <section className="px-6 lg:px-12 py-20 bg-black text-white"><div className="max-w-6xl mx-auto"><SectionLabel><span className="text-gray-400">Measurement</span></SectionLabel><h2 className="text-3xl font-extrabold">Measure What Moves the Business</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-px bg-white/10 mt-8">{data.metrics.map(x=><div key={x} className="bg-black p-5 font-semibold">{x}</div>)}</div></div></section>
 <section className="px-6 lg:px-12 py-20"><div className="max-w-4xl mx-auto"><SectionLabel>FAQ</SectionLabel><SectionTitle>{data.name} Marketing Questions</SectionTitle><div className="mt-8">{data.faq.map(x=><details key={x.q} className="group border-b border-gray-200"><summary className="py-5 font-bold cursor-pointer flex justify-between">{x.q}<span>+</span></summary><p className="pb-5 text-gray-500 leading-relaxed">{x.a}</p></details>)}</div></div></section>
 <section className="px-6 lg:px-12 py-24 bg-black text-white text-center"><div className="max-w-3xl mx-auto"><h2 className="text-[clamp(2rem,4vw,3rem)] font-extrabold">{data.cta}</h2><p className="text-gray-400 text-lg mt-4 mb-8">Tell us where you are now, what you want to grow, and what is getting in the way.</p><Link href="/get-a-quote" className="inline-block bg-white text-black px-10 py-5 font-bold">Request a Quote &rarr;</Link></div></section></article>;
}