"use client";
import { useEffect,useState } from "react";
import {ArrowUpRight,Users,Clock3,Target,WalletCards,Sparkles} from "lucide-react";

type Data=any;
const money=(n:number)=>n?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n):"$0";
const label=(s:string)=>String(s||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());

export function AnalyticsPanel({headers}:{headers:Record<string,string>}){
 const [data,setData]=useState<Data|null>(null),[days,setDays]=useState(30),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/admin/analytics?days=${days}`,{headers});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||"Dashboard unavailable");setData(d)}catch(e:any){setError(e?.message||"Dashboard unavailable")}finally{setLoading(false)}}
 useEffect(()=>{load()},[days]);
 if(loading)return <div className="py-16 text-center text-gray-500">Loading operations dashboard...</div>;
 if(!data||error)return <div className="min-h-[520px] grid place-items-center"><div className="max-w-lg rounded-3xl border bg-white p-8 text-center shadow-sm"><div className="mx-auto h-14 w-14 rounded-2xl bg-black text-white grid place-items-center"><Sparkles size={22}/></div><h2 className="mt-5 text-2xl font-black">Markit-Dashboard needs a refresh</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{error||"We could not load your workspace data."} Your leads are not lost.</p><button onClick={load} className="mt-6 rounded-xl bg-black px-5 py-3 text-sm font-bold text-white">Try again</button></div></div>;
 const maxDay=Math.max(...data.leadsByDay.map((x:any)=>x.count),1);
 return <div className="space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gray-400">Markit Media · Command Center</p><h2 className="mt-1 text-3xl font-black tracking-tight">Good to see you.</h2><p className="mt-1 text-sm text-gray-500">A clean view of leads, follow-ups, pipeline and content that needs attention.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))} className="rounded-lg border bg-white px-3 py-2 text-sm"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last year</option></select></div>

  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
   {[["New Leads",data.summary.newLeads,`${data.summary.periodChange>=0?"+":""}${data.summary.periodChange}% vs previous period`],["Needs Follow-up",data.attention.overdue,"Overdue scheduled follow-ups"],["Qualified",data.summary.qualified,`${data.summary.proposals} currently at proposal stage`],["Pipeline Value",money(data.summary.pipelineValue),`${money(data.summary.wonValue)} won in selected period`]].map(([a,b,c],i)=><div key={String(a)} className={`rounded-2xl border p-5 ${i===0?"bg-black text-white":"bg-white"}`}><div className="text-xs font-bold uppercase tracking-wider opacity-50">{a}</div><div className="mt-2 text-3xl font-extrabold">{b}</div><div className="mt-2 text-xs opacity-60">{c}</div></div>)}
  </div>

  <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
   <section className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><h3 className="font-extrabold">Needs Your Attention</h3><p className="text-xs text-gray-400">Items most likely to need action now</p></div><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700">{data.attention.needsContact+data.attention.overdue} actionable</span></div><div className="mt-5 grid grid-cols-2 gap-3">{[["Uncontacted leads",data.attention.needsContact,"New or in progress"],["Overdue follow-ups",data.attention.overdue,"Past scheduled date"],["Stale leads",data.attention.stale,"7+ days without contact"],["Unassigned",data.attention.unassigned,"Open leads without owner"]].map(([a,b,c])=><div key={String(a)} className="rounded-xl bg-gray-50 p-4"><div className="text-2xl font-extrabold">{b}</div><div className="mt-1 text-sm font-bold">{a}</div><div className="text-xs text-gray-400">{c}</div></div>)}</div></section>
   <section className="rounded-2xl border bg-white p-6"><h3 className="font-extrabold">Lead Activity</h3><p className="text-xs text-gray-400">{data.period}</p><div className="mt-5 flex h-40 items-end gap-1">{data.leadsByDay.length?data.leadsByDay.map((x:any)=><div key={x.date} title={`${x.date}: ${x.count}`} className="flex h-full flex-1 items-end"><div className="w-full rounded-t bg-black" style={{height:`${Math.max(4,(x.count/maxDay)*100)}%`}}/></div>):<div className="m-auto text-sm text-gray-400">No lead activity yet</div>}</div></section>
  </div>

  <section className="rounded-2xl border bg-white p-6"><div className="flex items-end justify-between"><div><h3 className="font-extrabold">Sales Pipeline</h3><p className="text-xs text-gray-400">Current stage distribution and estimated opportunity value</p></div><div className="text-right"><div className="text-xs uppercase text-gray-400">Open value</div><div className="font-extrabold">{money(data.summary.pipelineValue)}</div></div></div><div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-6">{data.pipeline.map((x:any)=><div key={x.stage} className="rounded-xl border p-4"><div className="text-xs font-bold uppercase text-gray-400">{label(x.stage)}</div><div className="mt-2 text-2xl font-extrabold">{x.count}</div><div className="mt-1 text-xs text-gray-500">{money(x.value)}</div></div>)}</div></section>

  <div className="grid gap-6 lg:grid-cols-2">
   <section className="rounded-2xl border bg-white p-6"><h3 className="font-extrabold">Upcoming Follow-ups</h3><div className="mt-4 space-y-2">{data.followUps.length?data.followUps.map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-xl bg-gray-50 p-3"><div><div className="text-sm font-bold">{x.name}</div><div className="text-xs text-gray-400">{x.company||x.service} · {x.assignedTo||"Unassigned"}</div></div><div className="text-right text-xs font-bold">{new Date(x.nextFollowUpAt).toLocaleDateString()}<div className="font-normal text-gray-400">{new Date(x.nextFollowUpAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</div></div></div>):<p className="py-8 text-center text-sm text-gray-400">No follow-ups scheduled yet. Add them from Lead Inbox.</p>}</div></section>
   <section className="rounded-2xl border bg-white p-6"><h3 className="font-extrabold">Recent Leads</h3><div className="mt-4 space-y-2">{data.recentLeads.map((x:any)=><div key={x.id} className="flex items-center justify-between border-b py-3 last:border-0"><div><div className="text-sm font-bold">{x.name}</div><div className="text-xs text-gray-400">{x.service} · {x.source}</div></div><div className="text-right"><div className="text-xs font-bold">{label(x.status)}</div><div className="text-xs text-gray-400">{x.assignedTo||"Unassigned"}</div></div></div>)}</div></section>
  </div>

  <div className="grid gap-6 lg:grid-cols-3">
   {[["Lead Sources",data.leadsBySource,"source"],["Top Services",data.leadsByService,"service"],["Status Breakdown",data.leadsByStatus,"status"]].map(([title,items,key]:any)=><section key={title} className="rounded-2xl border bg-white p-6"><h3 className="font-extrabold">{title}</h3><div className="mt-4 space-y-3">{items.slice(0,7).map((x:any)=><div key={x[key]} className="flex justify-between gap-4 text-sm"><span className="truncate text-gray-600">{label(x[key])}</span><b>{x.count}</b></div>)}</div></section>)}
  </div>

  <div className="grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-7">{[["Discovery",data.summary.discoveryBriefs],["Newsletter",data.summary.newsletterSubscribers],["Blogs",data.summary.totalPosts],["Published",data.summary.publishedPosts],["Drafts",data.summary.draftPosts],["Media",data.summary.totalMedia],["Categories",data.summary.categories]].map(([a,b])=><div key={String(a)} className="rounded-xl border bg-white p-4"><div className="text-xl font-extrabold">{b}</div><div className="text-xs uppercase text-gray-400">{a}</div></div>)}</div>
 </div>
}
