"use client";import {useCallback,useEffect,useState} from "react";
type Kind="case_studies"|"portfolio"|"testimonials"|"clients";type Item={id:string;title:string;slug?:string;status?:string;summary?:string;image?:string;url?:string};
const labels:Record<Kind,string>={case_studies:"Case Studies",portfolio:"Portfolio / Work",testimonials:"Testimonials",clients:"Clients"};
export function ContentPanel({headers,kind}:{headers:Record<string,string>;kind:Kind}){const [items,setItems]=useState<Item[]>([]),[edit,setEdit]=useState<Partial<Item>|null>(null),[loading,setLoading]=useState(true);
const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/admin/content?type=${kind}`,{headers});const d=await r.json();setItems(d.items||[]);setLoading(false)},[kind]);useEffect(()=>{load()},[load]);
async function save(){if(!edit?.title)return;const method=edit.id?"PATCH":"POST",r=await fetch("/api/admin/content",{method,headers,body:JSON.stringify({...edit,type:kind})});if(!r.ok){const d=await r.json();return alert(d.error||"Could not save")}setEdit(null);load()}
async function del(id:string){if(!confirm("Delete this item?"))return;await fetch("/api/admin/content",{method:"DELETE",headers,body:JSON.stringify({id,type:kind})});load()}
return <div className="space-y-6"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-extrabold">{labels[kind]}</h2><p className="text-sm text-gray-500 mt-1">MongoDB managed website content.</p></div><button onClick={()=>setEdit({status:"draft"})} className="bg-black text-white px-4 py-2 text-sm font-bold">+ Add</button></div>
{edit&&<div className="bg-white border p-5 grid md:grid-cols-2 gap-4"><input value={edit.title||""} onChange={e=>setEdit({...edit,title:e.target.value})} placeholder="Title" className="border p-3"/><input value={edit.slug||""} onChange={e=>setEdit({...edit,slug:e.target.value})} placeholder="Slug / identifier" className="border p-3"/><input value={edit.image||""} onChange={e=>setEdit({...edit,image:e.target.value})} placeholder="Image URL" className="border p-3"/><input value={edit.url||""} onChange={e=>setEdit({...edit,url:e.target.value})} placeholder="Destination URL" className="border p-3"/><textarea value={edit.summary||""} onChange={e=>setEdit({...edit,summary:e.target.value})} placeholder="Summary / testimonial text" className="border p-3 md:col-span-2" rows={4}/><select value={edit.status||"draft"} onChange={e=>setEdit({...edit,status:e.target.value})} className="border p-3 bg-white"><option value="draft">Draft</option><option value="published">Published</option><option value="active">Active</option></select><div className="flex gap-2"><button onClick={save} className="bg-black text-white px-5 py-2 font-bold">Save</button><button onClick={()=>setEdit(null)} className="border px-5 py-2">Cancel</button></div></div>}
{loading?<div className="py-12 text-center text-gray-500">Loading…</div>:<div className="bg-white border overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b"><th className="text-left p-3">Title</th><th className="text-left p-3">Status</th><th className="text-left p-3">URL</th><th className="text-left p-3">Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-b"><td className="p-3 font-medium">{x.title}<div className="text-xs text-gray-400">{x.slug}</div></td><td className="p-3 capitalize">{x.status||"draft"}</td><td className="p-3 max-w-xs truncate text-gray-500">{x.url||"—"}</td><td className="p-3"><button onClick={()=>setEdit(x)} className="font-bold mr-3">Edit</button><button onClick={()=>del(x.id)} className="text-red-600">Delete</button></td></tr>)}{!items.length&&<tr><td colSpan={4} className="p-10 text-center text-gray-400">No items yet</td></tr>}</tbody></table></div>}</div>}