"use client";
import { useCallback,useEffect,useState } from "react";
import {Download,FileText,Image as ImageIcon,Mail,CheckSquare,Square,Trash2} from "lucide-react";

type Lead={id:string;collection:string;formType:string;name:string;email:string;company:string;phone:string;service:string;budget:string;timeline:string;message:string;status:string;tags:string[];internalNotes:string;assignedTo:string;source:string;landingPage:string;referrer:string;utmSource:string;utmMedium:string;utmCampaign:string;marketingConsent:boolean;createdAt:string;lastContactedAt?:string|null;nextFollowUpAt?:string|null;estimatedDealValue?:number;details:Record<string,any>};
type CommItem={id:string;direction:string;channel:string;to:string;subject:string;message:string;actor:string;status:string;createdAt:string};
const STATUS=[["new","New"],["in_progress","In Progress"],["contacted","Contacted"],["qualified","Qualified"],["proposal","Proposal Sent"],["won","Won"],["existing_client","Existing Client"],["partnership","Partnership Inquiry"],["sales_outreach","Sales Outreach"],["spam","Spam"],["lost","Lost"],["completed","Completed"],["closed","Closed"]];
const LABELS:Record<string,string>={
 "contact":"Contact Form","contact form":"Contact Form","website form":"Website Form","get a quote":"Request a Quote","get_a_quote":"Request a Quote","quote":"Request a Quote","brand discovery brief":"Discovery Brief","discovery_briefs":"Discovery Brief","form_submissions":"Website / Quote Form","newsletter_subscribers":"Newsletter","organic":"Organic Search","google":"Google","direct":"Direct","meta":"Meta","facebook":"Facebook","instagram":"Instagram","linkedin":"LinkedIn","seo":"SEO","ppc":"Paid Search","smm":"Social Media"
};
const pretty=(v:string)=>{if(!v)return "—";const raw=String(v).trim();const key=raw.toLowerCase();return LABELS[key]||raw.replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase())};
const show=(v:any)=>Array.isArray(v)?v.join(", "):typeof v==="boolean"?(v?"Yes":"No"):v?String(v):"—";

export function LeadsPanel({headers}:{headers:Record<string,string>}){
 const [leads,setLeads]=useState<Lead[]>([]),[selected,setSelected]=useState<Lead|null>(null),[loading,setLoading]=useState(true);
 const [page,setPage]=useState(1),[totalPages,setTotalPages]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[type,setType]=useState("");
 const [counts,setCounts]=useState<Record<string,number>>({});
 const [compose,setCompose]=useState<{subject:string;message:string}|null>(null),[sending,setSending]=useState(false);
 const [comms,setComms]=useState<CommItem[]>([]),[commsLoading,setCommsLoading]=useState(false);
 const [checked,setChecked]=useState<Set<string>>(new Set()),[bulkAction,setBulkAction]=useState(""),[bulkAssign,setBulkAssign]=useState(""),[bulkRunning,setBulkRunning]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const p=new URLSearchParams({page:String(page),limit:"25"});if(search)p.set("search",search);if(status)p.set("status",status);if(type)p.set("type",type);const r=await fetch("/api/admin/leads?"+p,{headers});const d=await r.json();setLeads(d.leads||[]);setTotal(d.total||0);setCounts(d.counts||{});setTotalPages(d.totalPages||1);setLoading(false)},[page,search,status,type,headers]);
 useEffect(()=>{load()},[load]);
 async function update(lead:Lead,changes:Record<string,string|number|string[]>){const r=await fetch("/api/admin/leads",{method:"PATCH",headers,body:JSON.stringify({id:lead.id,collection:lead.collection,...changes})});if(r.ok){setSelected(x=>x&&x.id===lead.id?{...x,...changes}:x);load()}}
 async function sendEmail(){if(!selected||!compose)return;setSending(true);const r=await fetch("/api/admin/email",{method:"POST",headers,body:JSON.stringify({to:selected.email,subject:compose.subject,message:compose.message,leadId:selected.id,leadCollection:selected.collection})});const d=await r.json();setSending(false);if(!r.ok)return alert(d.error||"Could not send email");setCompose(null);setSelected({...selected,status:"contacted",lastContactedAt:new Date().toISOString()});loadComms(selected.id);load();alert("Email sent and saved to communication history.");}
 async function loadComms(leadId:string){setCommsLoading(true);try{const r=await fetch(`/api/admin/email?leadId=${leadId}`,{headers});const d=await r.json();setComms(d.items||[])}catch{setComms([])}finally{setCommsLoading(false)}}
 function openLead(l:Lead){setSelected(l);setComms([]);loadComms(l.id)}
 function toggleCheck(key:string){setChecked(prev=>{const next=new Set(prev);next.has(key)?next.delete(key):next.add(key);return next})}
 function toggleAll(){if(checked.size===leads.length){setChecked(new Set())}else{setChecked(new Set(leads.map(l=>l.collection+":"+l.id)))}}
 async function runBulk(){if(!bulkAction||checked.size===0)return;if(!confirm(`Apply "${bulkAction}" to ${checked.size} lead(s)?`))return;setBulkRunning(true);const items=leads.filter(l=>checked.has(l.collection+":"+l.id));for(const lead of items){const changes:Record<string,any>={};if(bulkAction==="assign"&&bulkAssign)changes.assignedTo=bulkAssign;else if(bulkAction!=="assign")changes.status=bulkAction;if(Object.keys(changes).length)await fetch("/api/admin/leads",{method:"PATCH",headers,body:JSON.stringify({id:lead.id,collection:lead.collection,...changes})})}setChecked(new Set());setBulkAction("");setBulkAssign("");setBulkRunning(false);load()}
 function fileName(ext:string){const base=(selected?.name||selected?.company||"lead").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");return `markit-media-${base||"lead"}-${new Date().toISOString().slice(0,10)}.${ext}`}
 function leadText(){if(!selected)return "";const lines=[`MARKIT MEDIA — ${selected.formType}`,`Submitted: ${selected.createdAt?new Date(selected.createdAt).toLocaleString():"—"}`,"",`Name: ${show(selected.name)}`,`Company: ${show(selected.company)}`,`Email: ${show(selected.email)}`,`Phone: ${show(selected.phone)}`,`Service: ${show(selected.service)}`,`Budget: ${show(selected.budget)}`,`Timeline: ${show(selected.timeline)}`];if(selected.message)lines.push("","WHAT THEY TOLD US",selected.message);if(selected.collection==="discovery_briefs"){lines.push("","DISCOVERY ANSWERS");Object.entries(selected.details||{}).forEach(([k,v])=>{if(v!==""&&v!=null&&(!Array.isArray(v)||v.length))lines.push(`${pretty(k)}: ${show(v)}`)})}lines.push("","SOURCE / ATTRIBUTION",`Source: ${show(selected.utmSource||selected.source)}`,`Landing page: ${show(selected.landingPage)}`,`Campaign: ${show(selected.utmCampaign)}`);return lines.join("\n")}
 function downloadTxt(){if(!selected)return;const b=new Blob([leadText()],{type:"text/plain;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=fileName("txt");a.click();URL.revokeObjectURL(u)}
 function printPdf(){if(!selected)return;const w=window.open("","_blank","width=900,height=1000");if(!w)return;const esc=(v:any)=>String(v??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[m]||m));const discovery=selected.collection==="discovery_briefs"?Object.entries(selected.details||{}).filter(([,v])=>v!==""&&v!=null&&(!Array.isArray(v)||v.length)).map(([k,v])=>`<div class="item"><small>${esc(pretty(k))}</small><b>${esc(show(v))}</b></div>`).join(""):"";w.document.write(`<!doctype html><html><head><title>${esc(fileName("pdf"))}</title><style>@page{margin:18mm}body{font:14px Arial;color:#111;margin:0}.brand{background:#111;color:white;padding:28px;border-radius:18px}.brand small{letter-spacing:2px}.brand h1{margin:8px 0 4px;font-size:28px}.section{margin-top:24px}.section h2{font-size:16px;border-bottom:2px solid #111;padding-bottom:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.item{border:1px solid #ddd;border-radius:10px;padding:12px}.item small{display:block;text-transform:uppercase;color:#777;font-weight:bold;font-size:9px;letter-spacing:1px}.item b{display:block;margin-top:5px;word-break:break-word}.message{white-space:pre-wrap;line-height:1.6;border:1px solid #ddd;padding:16px;border-radius:10px}.foot{margin-top:28px;color:#888;font-size:10px}</style></head><body><div class="brand"><small>MARKIT MEDIA · LEAD BRIEF</small><h1>${esc(selected.name||selected.company||"Website Lead")}</h1><div>${esc(selected.formType)} · ${esc(selected.createdAt?new Date(selected.createdAt).toLocaleString():"")}</div></div><div class="section"><h2>Lead details</h2><div class="grid">${[["Company",selected.company],["Email",selected.email],["Phone",selected.phone],["Service",selected.service],["Budget",selected.budget],["Timeline",selected.timeline]].filter(([,v])=>v).map(([k,v])=>`<div class="item"><small>${k}</small><b>${esc(show(v))}</b></div>`).join("")}</div></div>${selected.message?`<div class="section"><h2>What they told us</h2><div class="message">${esc(selected.message)}</div></div>`:""}${discovery?`<div class="section"><h2>Discovery answers</h2><div class="grid">${discovery}</div></div>`:""}<div class="section"><h2>Acquisition</h2><div class="grid">${[["Source",selected.utmSource||selected.source],["Landing page",selected.landingPage],["Campaign",selected.utmCampaign],["Medium",selected.utmMedium]].filter(([,v])=>v).map(([k,v])=>`<div class="item"><small>${k}</small><b>${esc(show(v))}</b></div>`).join("")}</div></div><div class="foot">Exported from Markit-Dashboard · Markit Media</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}
 async function downloadImage(){if(!selected)return;const text=leadText().split("\n"),width=1200,pad=70,line=34;const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");if(!ctx)return;ctx.font="24px Arial";const wrap:string[]=[];for(const raw of text){if(!raw){wrap.push("");continue}let current="";for(const word of raw.split(" ")){const next=current?`${current} ${word}`:word;if(ctx.measureText(next).width>width-pad*2&&current){wrap.push(current);current=word}else current=next}wrap.push(current)}canvas.width=width;canvas.height=Math.max(720,180+wrap.length*line+pad);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#111";ctx.fillRect(0,0,width,130);ctx.fillStyle="#fff";ctx.font="bold 28px Arial";ctx.fillText("MARKIT MEDIA",pad,58);ctx.font="16px Arial";ctx.fillText("Lead Brief · Exported from Markit-Dashboard",pad,91);ctx.fillStyle="#111";let y=180;for(const row of wrap){const heading=row&&(!row.includes(":"))&&["WHAT THEY TOLD US","DISCOVERY ANSWERS","SOURCE / ATTRIBUTION"].includes(row);ctx.font=heading?"bold 22px Arial":"20px Arial";ctx.fillStyle=heading?"#111":"#333";ctx.fillText(row,pad,y);y+=heading?44:line}const a=document.createElement("a");a.download=fileName("png");a.href=canvas.toDataURL("image/png");a.click()}
 function csv(){const rows=[["Name","Email","Phone","Company","Form","Service","Status","Tags","Assigned","Source","Landing Page","UTM Source","UTM Medium","UTM Campaign","Date"]];leads.forEach(x=>rows.push([x.name,x.email,x.phone,x.company,x.formType,x.service,x.status,(x.tags||[]).join(" | "),x.assignedTo,x.source,x.landingPage,x.utmSource,x.utmMedium,x.utmCampaign,x.createdAt]));const b=new Blob([rows.map(r=>r.map(c=>'"'+String(c||"").replace(/"/g,'""')+'"').join(",")).join("\n")],{type:"text/csv"});const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="markit-leads.csv";a.click();URL.revokeObjectURL(u)}
 return <div className="space-y-6">
  <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[["All",total],["New",counts.new||0],["Qualified",counts.qualified||0],["Won",counts.won||0],["Sales Outreach",counts.sales_outreach||0],["Spam",counts.spam||0]].map(([l,v])=><div key={String(l)} className="rounded-xl border border-gray-200 bg-white p-4"><div className="text-2xl font-extrabold">{v}</div><div className="text-xs font-bold uppercase tracking-wide text-gray-400">{l}</div></div>)}</div>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">Lead Inbox</h2><p className="text-sm text-gray-500">Contact, quote, discovery and newsletter submissions with lead-quality classification</p></div><button onClick={csv} className="rounded-lg border px-3 py-2 text-sm font-bold">Export CSV</button></div>
  <div className="grid gap-3 md:grid-cols-3"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search name, email, company, phone..." className="rounded-lg border px-3 py-2 text-sm"/><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}} className="rounded-lg border bg-white px-3 py-2 text-sm"><option value="">All forms</option><option value="form_submissions">Website / Quote / Tool</option><option value="discovery_briefs">Discovery Brief</option><option value="newsletter_subscribers">Newsletter</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-lg border bg-white px-3 py-2 text-sm"><option value="">All statuses</option>{STATUS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
  {checked.size>0&&<div className="flex flex-wrap items-center gap-3 rounded-xl border border-black bg-black p-3 text-white"><span className="text-sm font-bold">{checked.size} selected</span><select value={bulkAction} onChange={e=>setBulkAction(e.target.value)} className="rounded-lg border border-white/20 bg-white/10 px-3 py-1.5 text-sm"><option value="">Bulk action...</option><option value="contacted">Mark Contacted</option><option value="qualified">Mark Qualified</option><option value="won">Mark Won</option><option value="spam">Mark Spam</option><option value="closed">Close</option><option value="assign">Assign To...</option></select>{bulkAction==="assign"&&<input value={bulkAssign} onChange={e=>setBulkAssign(e.target.value)} placeholder="Team member name" className="rounded-lg border border-white/20 bg-white/10 px-3 py-1.5 text-sm"/>}<button onClick={runBulk} disabled={!bulkAction||bulkRunning} className="rounded-lg bg-white px-4 py-1.5 text-sm font-bold text-black disabled:opacity-40">{bulkRunning?"Applying...":"Apply"}</button><button onClick={()=>setChecked(new Set())} className="text-sm text-white/60 hover:text-white">Clear</button></div>}
  <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="px-3 py-3 w-10"><button onClick={toggleAll} className="text-gray-400 hover:text-black">{checked.size===leads.length&&leads.length>0?<CheckSquare size={16}/>:<Square size={16}/>}</button></th>{["Customer","Form / Source","Contact","Service","Status","Owner","Date",""].map(x=><th key={x} className="px-4 py-3 text-left font-bold">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={9} className="p-10 text-center text-gray-400">Loading MongoDB leads...</td></tr>:leads.length?leads.map(l=>{const ck=l.collection+":"+l.id;return <tr key={ck} className={`border-t hover:bg-gray-50 ${checked.has(ck)?"bg-blue-50":""}`}><td className="px-3 py-3"><button onClick={()=>toggleCheck(ck)} className="text-gray-400 hover:text-black">{checked.has(ck)?<CheckSquare size={16}/>:<Square size={16}/>}</button></td><td className="px-4 py-3"><b>{l.name}</b><div className="text-xs text-gray-400">{l.company}</div></td><td className="px-4 py-3"><b>{pretty(l.formType)}</b><div className="text-xs text-gray-400">{pretty(l.source)}</div></td><td className="px-4 py-3"><div>{l.email}</div><div className="text-xs text-gray-400">{l.phone}</div></td><td className="px-4 py-3 max-w-48"><div className="truncate">{pretty(l.service)}</div>{l.tags?.length>0&&<div className="mt-1 flex max-w-52 flex-wrap gap-1">{l.tags.slice(0,3).map(t=><span key={t} className="rounded-full bg-zinc-100 px-2 py-0.5 text-[10px] font-bold text-zinc-600">{t}</span>)}</div>}</td><td className="px-4 py-3"><select value={l.status==="subscribed"?"new":l.status} onChange={e=>update(l,{status:e.target.value})} className="rounded border bg-white px-2 py-1 text-xs font-bold">{STATUS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></td><td className="px-4 py-3">{l.assignedTo||"Unassigned"}</td><td className="px-4 py-3 whitespace-nowrap">{l.createdAt?new Date(l.createdAt).toLocaleDateString():"—"}</td><td className="px-4 py-3"><button onClick={()=>openLead(l)} className="font-bold underline">Open</button></td></tr>}):<tr><td colSpan={9} className="p-10 text-center text-gray-400">No submissions found.</td></tr>}</tbody></table></div>
  {totalPages>1&&<div className="flex justify-center gap-3"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="border px-4 py-2 disabled:opacity-30">Previous</button><span className="py-2 text-sm">Page {page} / {totalPages}</span><button disabled={page===totalPages} onClick={()=>setPage(p=>p+1)} className="border px-4 py-2 disabled:opacity-30">Next</button></div>}
  {selected&&<div className="fixed inset-0 z-50 bg-black/55 p-4 flex items-center justify-center" onClick={()=>setSelected(null)}><div className="w-full max-w-4xl max-h-[92vh] overflow-y-auto rounded-2xl bg-white p-6 sm:p-8" onClick={e=>e.stopPropagation()}>
   <div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-gray-400">{selected.formType}</p><h3 className="text-2xl font-extrabold">{selected.name}</h3><p className="text-sm text-gray-500">{selected.company||"No company"} · {pretty(selected.source)}</p></div><div className="flex flex-wrap items-start gap-2"><button onClick={downloadImage} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><ImageIcon size={14}/> Image</button><button onClick={printPdf} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><FileText size={14}/> PDF</button><button onClick={downloadTxt} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><Download size={14}/> GPT / Text</button><button onClick={()=>setSelected(null)} className="ml-1 text-2xl">×</button></div></div>
   <div className="mt-6 grid gap-3 sm:grid-cols-3"><button onClick={()=>setCompose({subject:`Re: Your enquiry to Markit Media`,message:`Hi ${selected.name||"there"},\\n\\nThank you for reaching out to Markit Media.\\n\\n`})} className="rounded-xl bg-black text-white p-3 font-bold text-left">Reply by email<div className="text-xs font-normal text-zinc-300 break-all">{selected.email}</div></button>{selected.phone&&<a href={"https://wa.me/"+selected.phone.replace(/\D/g,"")} target="_blank" className="rounded-xl border p-3 font-bold">WhatsApp ↗<div className="text-xs font-normal text-gray-500">{selected.phone}</div></a>}<div className="rounded-xl border p-3"><b>Submitted</b><div className="text-xs text-gray-500">{selected.createdAt?new Date(selected.createdAt).toLocaleString():"—"}</div></div></div>
   <div className="mt-6 grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold uppercase text-gray-500">Lead status<select value={selected.status==="subscribed"?"new":selected.status} onChange={e=>update(selected,{status:e.target.value})} className="mt-2 w-full rounded-lg border bg-white p-3 text-sm normal-case">{STATUS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="text-xs font-bold uppercase text-gray-500">Assigned to<input defaultValue={selected.assignedTo} onBlur={e=>update(selected,{assignedTo:e.target.value})} placeholder="Team member" className="mt-2 w-full rounded-lg border p-3 text-sm normal-case"/></label><div className="text-xs font-bold uppercase text-gray-500">Service<div className="mt-2 rounded-lg bg-gray-50 p-3 text-sm font-semibold normal-case">{pretty(selected.service)}</div></div></div>
   <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold uppercase text-gray-500">Next follow-up<input type="datetime-local" defaultValue={selected.nextFollowUpAt?new Date(selected.nextFollowUpAt).toISOString().slice(0,16):""} onBlur={e=>update(selected,{nextFollowUpAt:e.target.value})} className="mt-2 w-full rounded-lg border p-3 text-sm normal-case"/></label><label className="text-xs font-bold uppercase text-gray-500">Estimated deal value (USD)<input type="number" min="0" defaultValue={selected.estimatedDealValue||""} onBlur={e=>update(selected,{estimatedDealValue:Number(e.target.value)||0})} placeholder="e.g. 2500" className="mt-2 w-full rounded-lg border p-3 text-sm normal-case"/></label></div>
   <div className="mt-6 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border p-5"><h4 className="font-extrabold">Lead details</h4><p className="text-xs text-gray-400 mt-1">The information the customer actually submitted.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{[["Email",selected.email],["Phone",selected.phone],["Company",selected.company],["Service",selected.service],["Budget",selected.budget],["Timeline",selected.timeline]].filter(([,v])=>v).map(([k,v])=><div key={String(k)}><p className="text-[10px] font-bold uppercase tracking-wider text-gray-400">{k}</p><p className="mt-1 break-words text-sm font-medium">{show(v)}</p></div>)}</div></section><section className="rounded-2xl bg-zinc-950 text-white p-5"><h4 className="font-extrabold">Acquisition</h4><p className="text-xs text-zinc-500 mt-1">Marketing context, kept separate from customer answers.</p><div className="mt-4 space-y-3">{[["Source",selected.utmSource||selected.source],["Landing page",selected.landingPage],["Campaign",selected.utmCampaign],["Medium",selected.utmMedium],["Referrer",selected.referrer]].filter(([,v])=>v).map(([k,v])=><div key={String(k)}><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-500">{k}</p><p className="mt-1 text-xs break-words text-zinc-200">{show(v)}</p></div>)}</div></section></div>
   {selected.message&&<div className="mt-5 rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-gray-400">What they told us</p><p className="mt-3 whitespace-pre-wrap text-[15px] leading-7">{selected.message}</p></div>}
   {selected.collection==="discovery_briefs"&&<div className="mt-6"><h4 className="font-extrabold">Discovery answers</h4><div className="mt-3 grid gap-3 sm:grid-cols-2">{["brandName","link","stage","launchDate","launchTbd","categories","positioning","audiences","markets","city","assets","needs","platforms","paidAds","adBudget","goals","referenceBrand","communication"].map(k=><div key={k} className="rounded-xl border p-3"><p className="text-xs font-bold uppercase text-gray-400">{pretty(k)}</p><p className="mt-1 text-sm">{show(selected.details?.[k])}</p></div>)}</div></div>}
   {compose&&<div className="mt-6 rounded-2xl border bg-zinc-50 p-5"><div className="flex items-center justify-between"><div><h4 className="font-extrabold">Email {selected.name}</h4><p className="text-xs text-gray-500">From Markit Media · Reply goes directly to {selected.email}</p></div><button onClick={()=>setCompose(null)} className="text-xl">×</button></div><input value={compose.subject} onChange={e=>setCompose({...compose,subject:e.target.value})} className="mt-4 w-full rounded-xl border bg-white p-3 text-sm" placeholder="Subject"/><textarea value={compose.message} onChange={e=>setCompose({...compose,message:e.target.value})} rows={8} className="mt-3 w-full rounded-xl border bg-white p-3 text-sm" placeholder="Write your reply…"/><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-gray-400">The sent email is logged against this lead.</p><button onClick={sendEmail} disabled={sending||!compose.subject||!compose.message} className="rounded-xl bg-black px-5 py-2.5 text-sm font-bold text-white disabled:opacity-40">{sending?"Sending…":"Send email"}</button></div></div>}
   <div className="mt-6 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Mail size={16}/><h4 className="font-extrabold">Communication History</h4></div><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-bold text-zinc-600">{comms.length} sent</span></div>{commsLoading?<p className="mt-4 text-sm text-gray-400">Loading...</p>:comms.length?<div className="mt-4 space-y-3">{comms.map(c=><div key={c.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div className="text-sm font-bold">{c.subject}</div><div className="shrink-0 text-xs text-gray-400">{new Date(c.createdAt).toLocaleString()}</div></div><p className="mt-2 text-sm text-gray-600 whitespace-pre-wrap line-clamp-3">{c.message}</p><div className="mt-2 flex items-center gap-3 text-xs text-gray-400"><span>To: {c.to}</span><span>By: {c.actor}</span><span className="rounded-full bg-green-50 px-2 py-0.5 text-green-700">{c.status}</span></div></div>)}</div>:<p className="mt-4 text-sm text-gray-400">No emails sent to this lead yet.</p>}</div>
   <div className="mt-6 rounded-2xl border bg-zinc-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-gray-500">Tags</p><p className="mt-1 text-xs text-gray-400">Use readable tags for context, not internal codes.</p></div><div className="flex flex-wrap gap-2">{["Hot Lead","Follow Up","Existing Client","Partner","USA","Pakistan"].map(tag=><button key={tag} type="button" onClick={()=>{const next=Array.from(new Set([...(selected.tags||[]),tag]));update(selected,{tags:next})}} className="rounded-full border bg-white px-3 py-1.5 text-xs font-bold">{tag}</button>)}</div></div><div className="mt-4 flex flex-wrap gap-2">{(selected.tags||[]).map(tag=><button key={tag} type="button" title="Remove tag" onClick={()=>update(selected,{tags:(selected.tags||[]).filter(t=>t!==tag)})} className="rounded-full bg-black px-3 py-1.5 text-xs font-bold text-white">{tag} ×</button>)}</div><input defaultValue={(selected.tags||[]).join(", ")} onBlur={e=>update(selected,{tags:e.target.value.split(",").map(x=>x.trim()).filter(Boolean).slice(0,12)})} placeholder="Add tags, separated by commas" className="mt-4 w-full rounded-xl border bg-white p-3 text-sm"/></div>
   <label className="mt-6 block text-xs font-bold uppercase text-gray-500">Internal team notes<textarea defaultValue={selected.internalNotes} onBlur={e=>update(selected,{internalNotes:e.target.value})} rows={5} placeholder="Call notes, follow-up, requirements, next action..." className="mt-2 w-full rounded-xl border p-3 text-sm normal-case"/></label>
  </div></div>}
 </div>
}
