"use client";
import { useCallback,useEffect,useState } from "react";
type Item={id:string;original_name:string;mime_type:string;size:number;alt_text:string;folder:string;url:string;created_at:string};
export function MediaPanel(){
 const [items,setItems]=useState<Item[]>([]),[folder,setFolder]=useState(""),[loading,setLoading]=useState(true),[ready,setReady]=useState(false),[publicReady,setPublicReady]=useState(false),[showAdd,setShowAdd]=useState(false);
 const [form,setForm]=useState({url:"",original_name:"",mime_type:"image/jpeg",alt_text:"",folder:"general"});
 const headers:Record<string,string>={},json={"Content-Type":"application/json"};
 const load=useCallback(async()=>{setLoading(true);const q=new URLSearchParams({limit:"100"});if(folder)q.set("folder",folder);const r=await fetch(`/api/admin/media?${q}`,{headers});const d=await r.json();setItems(d.media||[]);setReady(Boolean(d.storageReady));setPublicReady(Boolean(d.publicUrlConfigured));setLoading(false);},[folder]);
 useEffect(()=>{load()},[load]);
 async function add(){const r=await fetch("/api/admin/media",{method:"POST",headers:json,body:JSON.stringify(form)});const d=await r.json();if(!r.ok)return alert(d.error||"Could not add media");setForm({url:"",original_name:"",mime_type:"image/jpeg",alt_text:"",folder:"general"});setShowAdd(false);load();}
 async function del(id:string){if(!confirm("Remove this media record?"))return;await fetch("/api/admin/media",{method:"DELETE",headers:json,body:JSON.stringify({id})});load();}
 return <div className="space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">Media Library ({items.length})</h2><p className="text-sm text-gray-500 mt-1">MongoDB catalog. R2 upload activates after the Cloudflare migration.</p></div><div className="flex gap-2"><select value={folder} onChange={e=>setFolder(e.target.value)} className="border px-3 py-2 text-sm bg-white"><option value="">All folders</option>{["general","blog","services","case-studies","portfolio","branding"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setShowAdd(!showAdd)} className="bg-black text-white px-4 py-2 text-sm font-bold">+ Add external asset</button></div></div>
  <div className={`border p-4 text-sm ${ready&&publicReady?"bg-green-50 border-green-200":"bg-amber-50 border-amber-200"}`}><b>Storage:</b> {ready&&publicReady?"R2 configuration detected.":"Cloudflare connection pending."} The CMS database is ready now; existing/external URLs can be catalogued without waiting.</div>
  {showAdd&&<div className="bg-white border p-5 grid md:grid-cols-2 gap-4">{(["url","original_name","alt_text"] as const).map(k=><input key={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k==="url"?"Asset URL":k==="original_name"?"File name":"Alt text"} className="border px-3 py-2"/>)}<select value={form.folder} onChange={e=>setForm({...form,folder:e.target.value})} className="border px-3 py-2 bg-white">{["general","blog","services","case-studies","portfolio","branding"].map(x=><option key={x}>{x}</option>)}</select><button onClick={add} disabled={!form.url} className="bg-black text-white px-4 py-2 font-bold disabled:opacity-40">Save asset</button></div>}
  {loading?<div className="py-12 text-center text-gray-500">Loading media…</div>:<div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">{items.map(x=><div key={x.id} className="bg-white border overflow-hidden"><div className="aspect-square bg-gray-100 flex items-center justify-center overflow-hidden">{x.mime_type?.startsWith("image/")?<img src={x.url} alt={x.alt_text||x.original_name} className="w-full h-full object-cover" loading="lazy"/>:<span className="text-xs text-gray-500">{x.mime_type||"Asset"}</span>}</div><div className="p-2"><p className="text-xs font-medium truncate">{x.original_name}</p><p className="text-xs text-gray-400">{x.folder}</p><div className="flex gap-2 mt-2"><button onClick={()=>navigator.clipboard.writeText(x.url)} className="text-xs underline">Copy URL</button><button onClick={()=>del(x.id)} className="text-xs text-red-600">Delete</button></div></div></div>)}{!items.length&&<div className="col-span-full py-12 text-center text-gray-400">No media records yet</div>}</div>}
 </div>
}