import { NextRequest, NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { getMongoDb } from "@/lib/mongodb";
import { verifyToken } from "@/lib/auth";
function auth(r:NextRequest){return verifyToken(r.cookies.get("admin_token")?.value||"");}
const allowed=["case_studies","portfolio","testimonials","clients"] as const;
function collection(type:string){return allowed.includes(type as any)?type:null;}
export async function GET(r:NextRequest){if(!auth(r))return NextResponse.json({error:"Unauthorized"},{status:401});const q=new URL(r.url).searchParams,type=collection(q.get("type")||"");if(!type)return NextResponse.json({error:"Invalid content type"},{status:400});const db=await getMongoDb(),docs=await db.collection(type).find({}).sort({sortOrder:1,createdAt:-1}).limit(250).toArray();return NextResponse.json({items:docs.map((x:any)=>({...x,id:x._id.toString(),_id:undefined}))});}
export async function POST(r:NextRequest){const s=auth(r);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await r.json(),type=collection(String(b.type||""));if(!type)return NextResponse.json({error:"Invalid content type"},{status:400});const now=new Date(),doc={title:String(b.title||"").trim(),slug:String(b.slug||"").trim(),status:String(b.status||"draft"),summary:String(b.summary||""),image:String(b.image||""),url:String(b.url||""),data:b.data&&typeof b.data==="object"?b.data:{},sortOrder:Number(b.sortOrder)||0,createdAt:now,updatedAt:now,createdBy:s.email};if(!doc.title)return NextResponse.json({error:"Title is required"},{status:400});const db=await getMongoDb(),x=await db.collection(type).insertOne(doc);await db.collection("activity_log").insertOne({action:type+".created",entityType:type,entityId:x.insertedId.toString(),actor:s.email,createdAt:now});return NextResponse.json({id:x.insertedId.toString(),success:true},{status:201});}
export async function PATCH(r:NextRequest){const s=auth(r);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await r.json(),type=collection(String(b.type||""));if(!type||!ObjectId.isValid(String(b.id)))return NextResponse.json({error:"Invalid request"},{status:400});const set:any={updatedAt:new Date(),updatedBy:s.email};for(const k of ["title","slug","status","summary","image","url","data","sortOrder"])if(k in b)set[k]=b[k];const db=await getMongoDb();await db.collection(type).updateOne({_id:new ObjectId(String(b.id))},{$set:set});return NextResponse.json({success:true});}
export async function DELETE(r:NextRequest){const s=auth(r);if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await r.json(),type=collection(String(b.type||""));if(!type||!ObjectId.isValid(String(b.id)))return NextResponse.json({error:"Invalid request"},{status:400});const db=await getMongoDb();await db.collection(type).deleteOne({_id:new ObjectId(String(b.id))});return NextResponse.json({success:true});}
