import type { Metadata } from "next";
import Link from "next/link";
import { Animate, Stagger } from "@/components/animate";
import { SectionLabel, SectionTitle, SectionDesc } from "@/components/section";
import { Breadcrumb } from "@/components/breadcrumb";
import { JsonLd } from "@/components/json-ld";
import { ToolCTA } from "@/components/tool-cta";

export const metadata: Metadata = {
  title: "Digital Marketing Statistics 2025 — Key Industry Data",
  description: "Essential digital marketing statistics for 2025. Data on SEO, PPC, social media, email marketing, content marketing, and e-commerce to inform your strategy.",
  alternates: { canonical: "https://themarkitmedia.com/en/resources/marketing-statistics" },
};

const categories = [
  {
    title: "SEO Statistics",
    stats: [
      { stat: "68%", desc: "of online experiences begin with a search engine (BrightEdge)" },
      { stat: "0.63%", desc: "of Google searchers click on a result from the second page (Backlinko)" },
      { stat: "53.3%", desc: "of all website traffic comes from organic search (BrightEdge)" },
      { stat: "14.6%", desc: "close rate for SEO leads, compared to 1.7% for outbound leads (Search Engine Journal)" },
      { stat: "75%", desc: "of users never scroll past the first page of search results (HubSpot)" },
      { stat: "46%", desc: "of all Google searches are seeking local information (GoGulf)" },
    ],
  },
  {
    title: "PPC & Paid Advertising",
    stats: [
      { stat: "$2", desc: "average return for every $1 spent on Google Ads (Google Economic Impact)" },
      { stat: "65%", desc: "of high-intent searches result in an ad click (WordStream)" },
      { stat: "80%", desc: "of businesses run PPC campaigns through Google Ads (Clutch)" },
      { stat: "4-6%", desc: "average conversion rate for Google Ads search campaigns across industries (WordStream)" },
      { stat: "50%", desc: "of people arriving at a retailer's site from paid ads are more likely to buy (Unbounce)" },
    ],
  },
  {
    title: "Social Media Marketing",
    stats: [
      { stat: "4.9B", desc: "people use social media worldwide (Statista)" },
      { stat: "54%", desc: "of social browsers use social media to research products (GlobalWebIndex)" },
      { stat: "73%", desc: "of marketers believe social media marketing has been effective for their business (Buffer)" },
      { stat: "2h 24m", desc: "average daily time spent on social media per user globally (DataReportal)" },
      { stat: "90%", desc: "of Instagram users follow at least one business account (Instagram)" },
    ],
  },
  {
    title: "Email Marketing",
    stats: [
      { stat: "$36", desc: "average ROI for every $1 spent on email marketing (Litmus)" },
      { stat: "4.48B", desc: "email users worldwide as of 2024 (Statista)" },
      { stat: "21.3%", desc: "average email open rate across all industries (Mailchimp)" },
      { stat: "2.6%", desc: "average click-through rate for email campaigns (Mailchimp)" },
      { stat: "77%", desc: "of marketers have seen an increase in email engagement over the last 12 months (HubSpot)" },
    ],
  },
  {
    title: "Content Marketing",
    stats: [
      { stat: "70%", desc: "of marketers actively invest in content marketing (HubSpot)" },
      { stat: "3x", desc: "more leads generated by content marketing compared to outbound marketing (Content Marketing Institute)" },
      { stat: "60%", desc: "of marketers report that content marketing generates demand and leads (CMI)" },
      { stat: "82%", desc: "of marketers actively use content marketing as a strategy (HubSpot)" },
      { stat: "47%", desc: "of buyers view 3-5 pieces of content before engaging with a sales rep (Demand Gen Report)" },
    ],
  },
  {
    title: "E-commerce",
    stats: [
      { stat: "$6.3T", desc: "global e-commerce sales projected for 2025 (eMarketer)" },
      { stat: "2.64%", desc: "average e-commerce conversion rate globally (Statista)" },
      { stat: "70%", desc: "of shopping carts are abandoned before purchase (Baymard Institute)" },
      { stat: "56%", desc: "of consumers say they have made a purchase on their mobile device (Statista)" },
      { stat: "88%", desc: "of online shoppers say detailed product descriptions are important (Salsify)" },
    ],
  },
  {
    title: "Video Marketing",
    stats: [
      { stat: "91%", desc: "of businesses use video as a marketing tool (Wyzowl)" },
      { stat: "82%", desc: "of people have been convinced to buy a product by watching a video (Wyzowl)" },
      { stat: "87%", desc: "of video marketers say video has a positive ROI (Wyzowl)" },
      { stat: "66%", desc: "of consumers prefer short-form video for learning about products (Sprout Social)" },
      { stat: "1B+", desc: "hours of YouTube video watched per day (YouTube)" },
    ],
  },
  {
    title: "Mobile & Voice Search",
    stats: [
      { stat: "60%", desc: "of all Google searches are done on mobile devices (Statista)" },
      { stat: "88%", desc: "of consumers who do a local search on their smartphone visit a store within a week (Google)" },
      { stat: "27%", desc: "of the global online population uses voice search on mobile (Google)" },
      { stat: "3.8s", desc: "average page load time on mobile — each additional second increases bounce rate (Google)" },
      { stat: "61%", desc: "of mobile users are more likely to contact a local business with a mobile-friendly site (Junto)" },
    ],
  },
];

export default function MarketingStatisticsPage() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: "Digital Marketing Statistics 2025",
    description: "Essential digital marketing statistics for 2025 to inform your strategy.",
    publisher: {
      "@type": "Organization",
      name: "Markit Media",
      url: "https://themarkitmedia.com",
    },
  };

  return (
    <article>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "Digital Marketing Statistics 2025",
          description: "Essential digital marketing statistics for 2025. Data on SEO, PPC, social media, email marketing, content marketing, and e-commerce to inform your strategy.",
          url: "https://themarkitmedia.com/en/resources/marketing-statistics",
          applicationCategory: "Marketing Tool",
          operatingSystem: "Web",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          provider: { "@type": "Organization", name: "Markit Media", url: "https://themarkitmedia.com" },
        }) }}
      />
      <JsonLd data={schema} />
      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Resources", href: "/resources" }, { label: "Marketing Statistics" }]} />

      <section aria-label="Resources" className="px-6 lg:px-12 pt-24 pb-12">
        <div className="max-w-4xl mx-auto">
          <Animate animation="fade-up">
            <SectionLabel>Resources</SectionLabel>
            <h1 className="font-[family-name:var(--font-display)] text-[clamp(2rem,5vw,3.5rem)] font-extrabold text-black tracking-tight leading-[1.1] mt-3">
              Digital Marketing Statistics 2025
            </h1>
            <SectionDesc>
              Data-driven decisions start with knowing the numbers. Here are the most important digital marketing statistics across every major channel.
            </SectionDesc>
          </Animate>
        </div>
      </section>

      <section aria-label="Content section" className="px-6 lg:px-12 pb-8">
        <div className="max-w-4xl mx-auto">
          <Animate animation="fade-up">
            <div className="flex flex-wrap gap-2">
              {categories.map((cat) => (
                <a
                  key={cat.title}
                  href={`#${cat.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}
                  className="px-4 py-2 border border-gray-200 text-base font-bold text-black hover:bg-black hover:text-white transition-colors motion-reduce:transition-none focus-visible:outline-2 focus-visible:outline-black focus-visible:outline-offset-2"
                >
                  {cat.title}
                </a>
              ))}
            </div>
          </Animate>
        </div>
      </section>

      {categories.map((cat, ci) => (
        <section
          key={cat.title}
          id={cat.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}
          className={`px-6 lg:px-12 py-16 ${ci % 2 === 1 ? "bg-gray-50" : ""}`}
          aria-label={cat.title}
        >
          <div className="max-w-4xl mx-auto">
            <Animate animation="fade-up">
              <h2 className="font-[family-name:var(--font-display)] text-xl font-extrabold text-black mb-8">
                {cat.title}
              </h2>
            </Animate>
            <Stagger stagger={60} animation="fade-up" className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {cat.stats.map((s, i) => (
                <div key={i} className="bg-white border border-gray-200 p-6">
                  <div className="font-[family-name:var(--font-display)] text-2xl font-extrabold text-black mb-2">
                    {s.stat}
                  </div>
                  <p className="text-base text-gray-500 leading-relaxed">{s.desc}</p>
                </div>
              ))}
            </Stagger>
          </div>
        </section>
      ))}

      <section aria-label="About This Data" className="px-6 lg:px-12 py-16">
        <div className="max-w-3xl mx-auto">
          <Animate animation="fade-up">
            <div className="p-8 bg-gray-50 border border-gray-200">
              <h2 className="font-[family-name:var(--font-display)] text-lg font-extrabold text-black mb-4">
                About This Data
              </h2>
              <p className="text-base text-gray-500 leading-relaxed mb-4">
                Statistics are sourced from publicly available industry reports and research by organizations including Google, HubSpot, BrightEdge, WordStream, Statista, Mailchimp, Wyzowl, and the Content Marketing Institute. Numbers represent the most recently published figures as of 2025.
              </p>
              <p className="text-base text-gray-500 leading-relaxed">
                Marketing performance varies significantly by industry, audience, and execution quality. Use these benchmarks as directional guidance, not guaranteed outcomes.
              </p>
            </div>
          </Animate>
        </div>
      </section>

      <section aria-label="Call to action" className="px-6 lg:px-12 py-20 bg-black text-white text-center">
        <div className="max-w-3xl mx-auto">
          <Animate animation="fade-up">
            <h2 className="font-[family-name:var(--font-display)] text-[clamp(1.75rem,4vw,2.5rem)] font-extrabold tracking-tight">
              Ready to Put These Numbers to Work?
            </h2>
            <p className="text-lg text-gray-400 mt-4 mb-8">
              Data is only valuable when it drives action. Let us build a strategy informed by what actually works.
            </p>
            <Link href="/contact" className="inline-flex items-center gap-3 bg-white text-black px-10 py-5 font-bold text-base hover:bg-gray-100 transition-colors motion-reduce:transition-none focus-visible:outline-2 focus-visible:outline-white focus-visible:outline-offset-2">
              Get a Free Strategy Session &rarr;
            </Link>
          </Animate>
        </div>
      </section>
    
      <ToolCTA
        toolName="Marketing Statistics"
        services={[
          { title: "Digital Marketing", desc: "Full-service digital marketing strategy for measurable business growth.", href: "/services/digital-marketing" },
          { title: "SEO", desc: "Organic search strategies that deliver compounding traffic over time.", href: "/services/seo" },
          { title: "Performance Marketing", desc: "Paid campaigns optimized for maximum return on ad spend.", href: "/services/performance-marketing" },
        ]}
        relatedTools={[
          { title: "Marketing Rfp Template", href: "/resources/marketing-rfp-template" },
          { title: "Marketing Stack Audit", href: "/resources/marketing-stack-audit" },
          { title: "Marketing Statistics 2026", href: "/resources/marketing-statistics-2026" },
          { title: "Marketing Timeline Planner", href: "/resources/marketing-timeline-planner" },
        ]}
        relatedBlog={[
          { title: "Digital Marketing Strategy Guide", href: "/blog" },
          { title: "How to Measure Marketing ROI", href: "/blog" },
        ]}
      />
    </article>
  );
}
